Kazooformation: binary_stream.test.cpp File Reference
binary_stream.test.cpp File Reference
#include <iostream>
#include <testing.hpp>
#include <ktl/binary_stream.hpp>
Functions
TEST (BinaryStream_test, addData)
TEST (BinaryStream_test, linearFlow)
Function Documentation
TEST() [1/2]
TEST (BinaryStream_test , addData)
References kazoo::BinaryStream::addBits(), kazoo::BinaryStream::addBytes(), kazoo::BinaryStream::getBytes(), kazoo::BinaryStream::getInputBitBufferSpace(), kazoo::BinaryStream::getNumBits(), kazoo::BinaryStream::getNumBytes(), and kazoo::BinaryStream::isByteAligned().
TEST() [2/2]
TEST (BinaryStream_test , linearFlow)
Test:
Test the linear flow of the binary stream. If 3 bits are sent in, then those same 3 bits should be able to be popped out. To avoid edge cases, only front or back alignment may be off at any given time.
References kazoo::BinaryStream::addBits(), kazoo::BinaryStream::getNumBits(), kazoo::BinaryStream::isByteAligned(), kazoo::BinaryStream::pad(), kazoo::BinaryStream::popBit(), and kazoo::BinaryStream::popBits().