Kazooformation: binary_model.test.cpp File Reference
binary_model.test.cpp File Reference
#include <testing.hpp>
#include <ktl/models/binary_model.hpp>
#include <ktl/symbol_stream.hpp>
Functions
TEST (BinaryModel_test, SymbolStreamIntegration)
Function Documentation
TEST()
TEST (BinaryModel_test , SymbolStreamIntegration)
=*= kazooformation =*=
Author
joshua
Date
1/21/25
Copyright
Copyright (c) 2025
References kazoo::SymbolStream< Token_t >::addSymbol(), kazoo::SymbolStream< Token_t >::getNumBits(), kazoo::SymbolStream< Token_t >::getNumBytes(), and kazoo::SymbolStream< Token_t >::getNumSymbols().