Kazooformation: sock::TcpSocketClient Class Reference
sock::TcpSocketClient Class Reference
#include <tcp_socket.hpp>
Public Member Functions
TcpSocketClient ()=default
~TcpSocketClient ()=default
bool connect (std::string server_address_string, uint16_t port)
bool disconnect ()
bool transaction (const std::string &data, std::string &response)
Private Member Functions
bool receive (std::string &data)
bool send (const std::string &data)
Private Attributes
bool connected_ = false
int sock_ = -1
Constructor & Destructor Documentation
TcpSocketClient()
sock::TcpSocketClient::TcpSocketClient () default
~TcpSocketClient()
sock::TcpSocketClient::~TcpSocketClient () default
Member Function Documentation
connect()
bool sock::TcpSocketClient::connect (std::string server_address_string, uint16_t port) inline
References connect(), connected_, and sock_.
Referenced by connect().
transaction()
bool sock::TcpSocketClient::transaction (const std::string & data, std::string & response) inline
References connected_, receive(), and send().
disconnect()
bool sock::TcpSocketClient::disconnect () inline
References connected_, and sock_.
send()
bool sock::TcpSocketClient::send (const std::string & data) inline private
References send(), and sock_.
Referenced by send(), and transaction().
receive()
bool sock::TcpSocketClient::receive (std::string & data) inline private
References sock::K_MAX_RECEIVE, and sock_.
Referenced by transaction().
Member Data Documentation
sock_
int sock::TcpSocketClient::sock_ = -1 private
Referenced by connect(), disconnect(), receive(), and send().
connected_
bool sock::TcpSocketClient::connected_ = false private
Referenced by connect(), disconnect(), and transaction().
The documentation for this class was generated from the following file:
tcp_socket.hpp