Kazooformation: kazoo::model::Testing::Model Class Reference
kazoo::model::Testing::Model Class Reference final
#include <testing_model.hpp>
Public Types
using TokenValueMap = std::map< Token, uint32_t >
Maps a token to it's corresponding binary value.
Public Member Functions
Model ()
void decodeAudioToSymbols (const IAudioChannel &audio_channel, ISymbolStream &symbol_stream) const override
void encodeSymbol (EncoderContext &context, uint32_t token_id, IAudioChannel &audio_channel) const override
uint32_t getNumSamplesPerSymbol () const override
virtual uint32_t getSymbolBitMask () const
size_t getSymbolBitWidth () const override
uint32_t getSymbolId (uint32_t value) const override
Token getToken (uint32_t value) const
uint32_t getValue (uint32_t token_id) const override
Get the value corresponding to the numeric token id.
Private Attributes
const uint32_t symbol_bit_width_
const TokenValueMap token_values_
Member Typedef Documentation
TokenValueMap
using kazoo::SymbolModel< Token >::TokenValueMap = std::map<Token , uint32_t> inherited
Maps a token to it's corresponding binary value.
Constructor & Destructor Documentation
Model()
kazoo::model::Testing::Model::Model () inline
References kazoo::model::Testing::SYMBOL_0, and kazoo::model::Testing::SYMBOL_1.
Member Function Documentation
encodeSymbol()
void kazoo::model::Testing::Model::encodeSymbol (EncoderContext & context, uint32_t token_id, IAudioChannel & audio_channel) const inline override virtual
Implements kazoo::ISymbolModel.
References kazoo::WaveTools::generateSinWaveSamples(), KTL_ASSERT, kazoo::model::Testing::SYMBOL_0, kazoo::model::Testing::SYMBOL_1, and kazoo::EncoderContext::wave_angle.
decodeAudioToSymbols()
void kazoo::model::Testing::Model::decodeAudioToSymbols (const IAudioChannel & audio_channel, ISymbolStream & symbol_stream) const inline override virtual
Implements kazoo::ISymbolModel.
References kazoo::ISymbolStream::addSymbolId(), kazoo::Fft::FftResults::FreqAmp::frequency, kazoo::IAudioChannel::getSamplesRef(), kazoo::Fft::FftResults::max_amplitude, kazoo::model::Testing::MAX_SYM_FREQ_DEVIATION, kazoo::Fft::performFftFrequency(), kazoo::model::Testing::SAMPLES_PER_SYMBOL, kazoo::model::Testing::SYM_0_FREQ, kazoo::model::Testing::SYM_1_FREQ, kazoo::model::Testing::SYMBOL_0, kazoo::model::Testing::SYMBOL_1, and kazoo::model::Testing::UNKNOWN.
Referenced by TEST().
getSymbolBitWidth()
size_t kazoo::SymbolModel< Token >::getSymbolBitWidth () const inline override virtual inherited
Implements kazoo::ISymbolModel.
getValue()
uint32_t kazoo::SymbolModel< Token >::getValue (uint32_t token_id) const inline override virtual inherited
Get the value corresponding to the numeric token id.
Parameters
token_id - The Token_t cast to an unsigned integer.
Returns
uint32_t - The value of the token.
Implements kazoo::ISymbolModel.
getToken()
Token kazoo::SymbolModel< Token >::getToken (uint32_t value) const inline inherited
getSymbolId()
uint32_t kazoo::SymbolModel< Token >::getSymbolId (uint32_t value) const inline override virtual inherited
From a binary value, get the corresponding symbol/token id.
Todo:
Need to remove 'token' verbiage, use 'symbol.id' and 'symbol.value' instead. This is for the sake of getting rid of templated interfaces which was a mistake from 5 hours of effort ago.
Parameters
value - The binary value to convert to a token id.
Returns
uint32_t - The token id corresponding to the value.
Implements kazoo::ISymbolModel.
getNumSamplesPerSymbol()
uint32_t kazoo::SymbolModel< Token >::getNumSamplesPerSymbol () const inline override virtual inherited
Implements kazoo::ISymbolModel.
getSymbolBitMask()
virtual uint32_t kazoo::ISymbolModel::getSymbolBitMask () const inline virtual inherited
References kazoo::ISymbolModel::getSymbolBitWidth().
Member Data Documentation
token_values_
const TokenValueMap kazoo::SymbolModel< Token >::token_values_ private inherited
symbol_bit_width_
const uint32_t kazoo::SymbolModel< Token >::symbol_bit_width_ private inherited
The documentation for this class was generated from the following file:
testing_model.hpp