Kazooformation: kazoo::SymbolStream< Token_t > Class Template Reference
kazoo::SymbolStream< Token_t > Class Template Reference
A simple Symbol Stream structure. Interfaces with the transcoder and binary stream.
#include <symbol_stream.hpp>
Public Member Functions
SymbolStream (const ISymbolModel &symbol_model)
Constructor.
void addSymbol (Token_t token)
Add a symbol to the end of the stream.
void addSymbolId (uint32_t token_id) override
void clear () override
Clear/Reset the symbol stream.
size_t getNumBits () const
size_t getNumBytes () const override
size_t getNumSymbols () const
Get the number of symbols in the stream.
bool popSymbol (Token_t &token)
bool popSymbolTokenId (uint32_t &token_id) override
bool populateBinaryStream (BinaryStream &binary_stream, size_t num_bytes, bool pop_symbols=true) override
std::pair< size_t, size_t > processBinaryStream (BinaryStream &binary_stream) override
Process a binary stream and convert it to symbols, removing the bits from the binary stream.
Private Attributes
const ISymbolModel & symbol_model_
std::deque< Token_t > symbols_ {}
Detailed Description
template<typename Token_t>
class kazoo::SymbolStream< Token_t >
A simple Symbol Stream structure. Interfaces with the transcoder and binary stream.
Template Parameters
Token_t - The token enum type
Constructor & Destructor Documentation
SymbolStream()
template<typename Token_t > kazoo::SymbolStream< Token_t >::SymbolStream (const ISymbolModel & symbol_model) inline
Constructor.
Parameters
symbol_model - The symbol table
Member Function Documentation
clear()
template<typename Token_t > void kazoo::SymbolStream< Token_t >::clear () inline override virtual
Clear/Reset the symbol stream.
Implements kazoo::ISymbolStream.
References kazoo::SymbolStream< Token_t >::symbols_.
addSymbol()
template<typename Token_t > void kazoo::SymbolStream< Token_t >::addSymbol (Token_t token) inline
Add a symbol to the end of the stream.
Parameters
token - The symbol token to add.
References kazoo::SymbolStream< Token_t >::symbols_.
Referenced by TEST(), and TEST_F().
addSymbolId()
template<typename Token_t > void kazoo::SymbolStream< Token_t >::addSymbolId (uint32_t token_id) inline override virtual
Implements kazoo::ISymbolStream.
References kazoo::SymbolStream< Token_t >::symbols_.
getNumSymbols()
template<typename Token_t > size_t kazoo::SymbolStream< Token_t >::getNumSymbols () const inline
Get the number of symbols in the stream.
Returns
size_t The number of symbols
References kazoo::SymbolStream< Token_t >::symbols_.
Referenced by TEST().
getNumBits()
template<typename Token_t > size_t kazoo::SymbolStream< Token_t >::getNumBits () const inline
References kazoo::ISymbolModel::getSymbolBitWidth(), kazoo::SymbolStream< Token_t >::symbol_model_, and kazoo::SymbolStream< Token_t >::symbols_.
Referenced by kazoo::SymbolStream< Token_t >::getNumBytes(), and TEST().
getNumBytes()
template<typename Token_t > size_t kazoo::SymbolStream< Token_t >::getNumBytes () const inline override virtual
Implements kazoo::ISymbolStream.
References kazoo::SymbolStream< Token_t >::getNumBits().
Referenced by kazoo::TranslationLayer::addData(), kazoo::TranslationLayer::encode(), kazoo::TranslationLayer::loadAndDecodeWav(), kazoo::SymbolStream< Token_t >::populateBinaryStream(), and TEST().
popSymbol()
template<typename Token_t > bool kazoo::SymbolStream< Token_t >::popSymbol (Token_t & token) inline
References kazoo::SymbolStream< Token_t >::symbols_.
Referenced by TEST().
popSymbolTokenId()
template<typename Token_t > bool kazoo::SymbolStream< Token_t >::popSymbolTokenId (uint32_t & token_id) inline override virtual
Implements kazoo::ISymbolStream.
References kazoo::SymbolStream< Token_t >::symbols_.
populateBinaryStream()
template<typename Token_t > bool kazoo::SymbolStream< Token_t >::populateBinaryStream (BinaryStream & binary_stream, size_t num_bytes, bool pop_symbols = true) inline override virtual
Implements kazoo::ISymbolStream.
References kazoo::BinaryStream::addBits(), kazoo::SymbolStream< Token_t >::getNumBytes(), kazoo::ISymbolModel::getSymbolBitWidth(), kazoo::ISymbolModel::getValue(), kazoo::SymbolStream< Token_t >::symbol_model_, and kazoo::SymbolStream< Token_t >::symbols_.
Referenced by kazoo::TranslationLayer::loadAndDecodeWav(), and TEST().
processBinaryStream()
template<typename Token_t > std::pair< size_t, size_t > kazoo::SymbolStream< Token_t >::processBinaryStream (BinaryStream & binary_stream) inline override virtual
Process a binary stream and convert it to symbols, removing the bits from the binary stream.
Parameters
binary_stream - The binary stream to process
Returns
std::pair<number of bytes processed, number of symbols processed>
Implements kazoo::ISymbolStream.
References kazoo::BinaryStream::getNumBytes(), kazoo::ISymbolModel::getSymbolBitWidth(), kazoo::ISymbolModel::getSymbolId(), kazoo::BinaryStream::isByteAligned(), KTL_ASSERT, kazoo::BinaryStream::popBits(), kazoo::SymbolStream< Token_t >::symbol_model_, and kazoo::SymbolStream< Token_t >::symbols_.
Referenced by kazoo::TranslationLayer::addData(), and TEST().
Member Data Documentation
symbol_model_
template<typename Token_t > const ISymbolModel& kazoo::SymbolStream< Token_t >::symbol_model_ private
Referenced by kazoo::SymbolStream< Token_t >::getNumBits(), kazoo::SymbolStream< Token_t >::populateBinaryStream(), and kazoo::SymbolStream< Token_t >::processBinaryStream().
symbols_
template<typename Token_t > std::deque<Token_t> kazoo::SymbolStream< Token_t >::symbols_ {} private
Referenced by kazoo::SymbolStream< Token_t >::addSymbol(), kazoo::SymbolStream< Token_t >::addSymbolId(), kazoo::SymbolStream< Token_t >::clear(), kazoo::SymbolStream< Token_t >::getNumBits(), kazoo::SymbolStream< Token_t >::getNumSymbols(), kazoo::SymbolStream< Token_t >::popSymbol(), kazoo::SymbolStream< Token_t >::popSymbolTokenId(), kazoo::SymbolStream< Token_t >::populateBinaryStream(), and kazoo::SymbolStream< Token_t >::processBinaryStream().
The documentation for this class was generated from the following file:
symbol_stream.hpp