Kazooformation: kazoo::model::K2PeakModel::Model Class Reference
kazoo::model::K2PeakModel::Model Class Reference final
#include <k2_model.hpp>
Public Types
using TokenValueMap = std::map< Token, uint32_t >
Maps a token to it's corresponding binary value.
Public Member Functions
Model ()
void decodeAudioToSymbols (const IAudioChannel &audio_channel, ISymbolStream &symbol_stream) const override
void encodeSymbol (EncoderContext &context, uint32_t token_id, IAudioChannel &audio_channel) const override
uint32_t getNumSamplesPerSymbol () const override
virtual uint32_t getSymbolBitMask () const
size_t getSymbolBitWidth () const override
uint32_t getSymbolId (uint32_t value) const override
Token getToken (uint32_t value) const
uint32_t getValue (uint32_t token_id) const override
Get the value corresponding to the numeric token id.
Private Member Functions
Token detectSymbolFromFftResults (const Fft::FftResults &results) const
Private Attributes
const uint32_t symbol_bit_width_
const TokenValueMap token_values_
Member Typedef Documentation
TokenValueMap
using kazoo::SymbolModel< Token >::TokenValueMap = std::map<Token , uint32_t> inherited
Maps a token to it's corresponding binary value.
Constructor & Destructor Documentation
Model()
kazoo::model::K2PeakModel::Model::Model () inline
References kazoo::model::K2PeakModel::SYMBOL_00, kazoo::model::K2PeakModel::SYMBOL_01, kazoo::model::K2PeakModel::SYMBOL_10, kazoo::model::K2PeakModel::SYMBOL_11, and kazoo::model::K2PeakModel::SYMBOL_BIT_WIDTH.
Member Function Documentation
encodeSymbol()
void kazoo::model::K2PeakModel::Model::encodeSymbol (EncoderContext & context, uint32_t token_id, IAudioChannel & audio_channel) const inline override virtual
Implements kazoo::ISymbolModel.
References kazoo::IAudioChannel::addSample(), kazoo::k2_pcm_data::KAZOO_A_PCM, kazoo::k2_pcm_data::KAZOO_D_PCM, kazoo::k2_pcm_data::KAZOO_E_PCM, kazoo::k2_pcm_data::KAZOO_G_PCM, KTL_ASSERT, kazoo::model::K2PeakModel::SYMBOL_00, kazoo::model::K2PeakModel::SYMBOL_01, kazoo::model::K2PeakModel::SYMBOL_10, and kazoo::model::K2PeakModel::SYMBOL_11.
decodeAudioToSymbols()
void kazoo::model::K2PeakModel::Model::decodeAudioToSymbols (const IAudioChannel & audio_channel, ISymbolStream & symbol_stream) const inline override virtual
Todo:
magic number/parameterize
Implements kazoo::ISymbolModel.
References kazoo::ISymbolStream::addSymbolId(), detectSymbolFromFftResults(), kazoo::IAudioChannel::getSamplesRef(), kazoo::Fft::performFftFrequency(), kazoo::model::K2PeakModel::SAMPLES_PER_SYMBOL, kazoo::model::K2PeakModel::SYMBOL_00, kazoo::model::K2PeakModel::SYMBOL_01, kazoo::model::K2PeakModel::SYMBOL_10, kazoo::model::K2PeakModel::SYMBOL_11, and kazoo::model::K2PeakModel::UNKNOWN.
Referenced by TEST_F().
getNumSamplesPerSymbol()
uint32_t kazoo::model::K2PeakModel::Model::getNumSamplesPerSymbol () const inline override virtual
Implements kazoo::ISymbolModel.
References kazoo::model::K2PeakModel::SAMPLES_PER_SYMBOL.
detectSymbolFromFftResults()
Token kazoo::model::K2PeakModel::Model::detectSymbolFromFftResults (const Fft::FftResults & results) const inline private
Todo:
Refactor this
References kazoo::Fft::FftResults::getNormalizedPeaks(), kazoo::model::K2PeakModel::MAX_FREQ_CUT_OFF, kazoo::model::K2PeakModel::MIN_AMPLITUDE_CUT_OFF_PARAMETER, kazoo::model::K2PeakModel::MIN_FREQ_CUT_OFF, kazoo::model::K2PeakModel::NUM_PEAK_FREQS_TO_CHECK, kazoo::model::K2PeakModel::PEAK_OF_INTEREST_ENVELOPE_HZ, kazoo::model::K2PeakModel::SYM_A_00_PEAKS_OF_INTEREST, kazoo::model::K2PeakModel::SYM_D_01_PEAKS_OF_INTEREST, kazoo::model::K2PeakModel::SYM_E_10_PEAKS_OF_INTEREST, kazoo::model::K2PeakModel::SYM_G_11_PEAKS_OF_INTEREST, kazoo::model::K2PeakModel::SYMBOL_00, kazoo::model::K2PeakModel::SYMBOL_01, kazoo::model::K2PeakModel::SYMBOL_10, kazoo::model::K2PeakModel::SYMBOL_11, and kazoo::model::K2PeakModel::UNKNOWN.
Referenced by decodeAudioToSymbols().
getSymbolBitWidth()
size_t kazoo::SymbolModel< Token >::getSymbolBitWidth () const inline override virtual inherited
Implements kazoo::ISymbolModel.
getValue()
uint32_t kazoo::SymbolModel< Token >::getValue (uint32_t token_id) const inline override virtual inherited
Get the value corresponding to the numeric token id.
Parameters
token_id - The Token_t cast to an unsigned integer.
Returns
uint32_t - The value of the token.
Implements kazoo::ISymbolModel.
getToken()
Token kazoo::SymbolModel< Token >::getToken (uint32_t value) const inline inherited
getSymbolId()
uint32_t kazoo::SymbolModel< Token >::getSymbolId (uint32_t value) const inline override virtual inherited
From a binary value, get the corresponding symbol/token id.
Todo:
Need to remove 'token' verbiage, use 'symbol.id' and 'symbol.value' instead. This is for the sake of getting rid of templated interfaces which was a mistake from 5 hours of effort ago.
Parameters
value - The binary value to convert to a token id.
Returns
uint32_t - The token id corresponding to the value.
Implements kazoo::ISymbolModel.
getSymbolBitMask()
virtual uint32_t kazoo::ISymbolModel::getSymbolBitMask () const inline virtual inherited
References kazoo::ISymbolModel::getSymbolBitWidth().
Member Data Documentation
token_values_
const TokenValueMap kazoo::SymbolModel< Token >::token_values_ private inherited
symbol_bit_width_
const uint32_t kazoo::SymbolModel< Token >::symbol_bit_width_ private inherited
The documentation for this class was generated from the following file:
k2_model.hpp