Kazooformation: kazoo::Deframer Class Reference
kazoo::Deframer Class Reference
#include <deframer.hpp>
Public Member Functions
Deframer (size_t preamble_size=0)
~Deframer ()=default
void getFrame (KtlFrame &frame)
bool processInput (BinaryStream &binary_stream)
Process the input binary stream in a stateful manner to extract frames from sequential stream inputs.
void reset ()
Private Types
enum class State {
FIND_FRAME_START = 0 , FIND_FRAME_SIZE = 1 , FIND_FRAME_DATA = 2 , FIND_FRAME_END = 3 ,
FOUND_FRAME = 4
}
Private Member Functions
void changeState (State new_state)
bool findFrameData (BinaryStream &binary_stream)
bool findFrameEnd (BinaryStream &binary_stream)
bool findFrameSize (BinaryStream &binary_stream)
bool findFrameStart (BinaryStream &binary_stream)
void printFrameData (BinaryStream &binary_stream)
Private Attributes
std::vector< uint8_t > frame_data_ {}
uint16_t frame_size_ {0}
The size of the frame data field, set when the frame size is found.
size_t preamble_size_ {0}
State state_ {State::FIND_FRAME_START}
Member Enumeration Documentation
State
enum class kazoo::Deframer::State strong private
Enumerator
FIND_FRAME_START
FIND_FRAME_SIZE
FIND_FRAME_DATA
FIND_FRAME_END
FOUND_FRAME
Constructor & Destructor Documentation
Deframer()
kazoo::Deframer::Deframer (size_t preamble_size = 0) inline
~Deframer()
kazoo::Deframer::~Deframer () default
Member Function Documentation
processInput()
bool kazoo::Deframer::processInput (BinaryStream & binary_stream) inline
Process the input binary stream in a stateful manner to extract frames from sequential stream inputs.
Parameters
binary_stream - The binary stream to process, this will pop bits from the stream.
Returns
true if a frame extraction was completed/a new frame was found, false otherwise.
References FIND_FRAME_DATA, FIND_FRAME_END, FIND_FRAME_SIZE, FIND_FRAME_START, findFrameData(), findFrameEnd(), findFrameSize(), findFrameStart(), and state_.
reset()
void kazoo::Deframer::reset () inline
References changeState(), FIND_FRAME_START, frame_data_, and frame_size_.
getFrame()
void kazoo::Deframer::getFrame (KtlFrame & frame) inline
References FOUND_FRAME, frame_data_, KTL_ASSERT, and state_.
changeState()
void kazoo::Deframer::changeState (State new_state) inline private
References state_.
Referenced by findFrameData(), findFrameEnd(), findFrameSize(), findFrameStart(), and reset().
findFrameStart()
bool kazoo::Deframer::findFrameStart (BinaryStream & binary_stream) inline private
References changeState(), FIND_FRAME_SIZE, findFrameSize(), kazoo::KtlFrame::FRAME_ALIGN_BYTE, kazoo::KtlFrame::FRAME_START_BYTE_A, kazoo::KtlFrame::FRAME_START_BYTE_B, kazoo::BinaryStream::getNumBytes(), KTL_ASSERT, kazoo::BinaryStream::popBit(), kazoo::BinaryStream::popBits(), and printFrameData().
Referenced by processInput().
findFrameSize()
bool kazoo::Deframer::findFrameSize (BinaryStream & binary_stream) inline private
References changeState(), FIND_FRAME_DATA, findFrameData(), frame_size_, kazoo::BinaryStream::getNumBytes(), KTL_ASSERT, kazoo::KtlFrame::MAX_FRAME_DATA_SIZE, kazoo::BinaryStream::popByte(), preamble_size_, and printFrameData().
Referenced by findFrameStart(), and processInput().
findFrameData()
bool kazoo::Deframer::findFrameData (BinaryStream & binary_stream) inline private
References changeState(), FIND_FRAME_END, findFrameEnd(), frame_data_, frame_size_, kazoo::BinaryStream::getNumBytes(), KTL_ASSERT, kazoo::KtlFrame::MAX_FRAME_DATA_SIZE, kazoo::BinaryStream::popByte(), and printFrameData().
Referenced by findFrameSize(), and processInput().
findFrameEnd()
bool kazoo::Deframer::findFrameEnd (BinaryStream & binary_stream) inline private
References changeState(), FOUND_FRAME, kazoo::KtlFrame::FRAME_END_BYTE_A, kazoo::BinaryStream::getNumBytes(), KTL_ASSERT, kazoo::BinaryStream::popByte(), and printFrameData().
Referenced by findFrameData(), and processInput().
printFrameData()
void kazoo::Deframer::printFrameData (BinaryStream & binary_stream) inline private
References kazoo::BinaryStream::getStreamDataConst().
Referenced by findFrameData(), findFrameEnd(), findFrameSize(), and findFrameStart().
Member Data Documentation
state_
State kazoo::Deframer::state_ {State::FIND_FRAME_START} private
Referenced by changeState(), getFrame(), and processInput().
frame_size_
uint16_t kazoo::Deframer::frame_size_ {0} private
The size of the frame data field, set when the frame size is found.
Referenced by findFrameData(), findFrameSize(), and reset().
frame_data_
std::vector<uint8_t> kazoo::Deframer::frame_data_ {} private
Referenced by findFrameData(), getFrame(), and reset().
preamble_size_
size_t kazoo::Deframer::preamble_size_ {0} private
Referenced by findFrameSize().
The documentation for this class was generated from the following file:
deframer.hpp