Kazooformation: kazoo::BinaryStream Class Reference
kazoo::BinaryStream Class Reference
A bit/byte stream structure for the project.
#include <binary_stream.hpp>
Public Member Functions
BinaryStream ()=default
void addBit (bool bit_value)
void addBits (uint8_t input_bits, size_t num_bits)
Add individual bits to the stream.
void addBytes (std::span< const uint8_t > input_bytes)
Add bytes to the stream. If the stream is not byte aligned when this function is called, an exception will be thrown.
void clear ()
Clear the stream data.
std::vector< uint8_t > getBytes (size_t num_bytes)
Get the next num_bytes bytes from the stream. Does not remove the bytes from the stream.
size_t getInputBitBufferSpace () const
If adding bits, this will return the number of bits that can be added to the stream before the stream is byte aligned.
size_t getNumBits () const
Get the number of bits in the stream.
size_t getNumBytes () const
Get the number of bytes in the stream. If the stream has spare bits that do not align to a byte, the number of bytes will be rounded up to the nearest byte.
size_t getOutputBitBufferUsedBits () const
const std::deque< uint8_t > & getStreamDataConst () const
Get a const reference to the underlying stream data.
bool isByteAligned () const
Get the byte alignment status of the stream.
void pad ()
If the last element is being used as a bit buffer, this will fill the remaining bits until the stream is byte aligned.
std::optional< bool > popBit ()
bool popBits (uint8_t &output, size_t num_bits)
Pop bits off the front, effectively the inverse of addBits.
bool popByte (uint8_t &output)
Private Attributes
size_t num_bits_in_input_buffer_ {0}
size_t num_bits_used_in_output_buffer_ {0}
std::deque< uint8_t > stream_data_ {}
Detailed Description
A bit/byte stream structure for the project.
This is a simple deque wrapper. First in, first out as unaligned bits can be added to the stream. (byte 0)[MSB/First Added] -> (byte 1) -> (byte 2) -> ... -> (byte n)[LSB/Last Added]
()
Constructor & Destructor Documentation
BinaryStream()
kazoo::BinaryStream::BinaryStream () default
Member Function Documentation
addBits()
void kazoo::BinaryStream::addBits (uint8_t input_bits, size_t num_bits) inline
Add individual bits to the stream.
Lest significant bit is added first.
Parameters
input_bits - The bits to be added to the stream, right aligned.
num_bits - The number of bits to add to the stream, must be between 1 and 8 inclusive.
References addBit().
Referenced by kazoo::SymbolStream< Token_t >::populateBinaryStream(), and TEST().
addBit()
void kazoo::BinaryStream::addBit (bool bit_value) inline
References KTL_ASSERT, num_bits_in_input_buffer_, num_bits_used_in_output_buffer_, and stream_data_.
Referenced by addBits(), and pad().
popBit()
std::optional< bool > kazoo::BinaryStream::popBit () inline
References KTL_ASSERT, num_bits_in_input_buffer_, num_bits_used_in_output_buffer_, and stream_data_.
Referenced by kazoo::Deframer::findFrameStart(), popBits(), and TEST().
popBits()
bool kazoo::BinaryStream::popBits (uint8_t & output, size_t num_bits) inline
Pop bits off the front, effectively the inverse of addBits.
Parameters
output - The output buffer to store the bits in. This becomes zeroed along with the number of bits being added.
num_bits - The number of bits to pop off the front of the stream.
Returns
true if there were enough bits to complete the operation, false otherwise.
Exceptions
You cannot pop bits off the front when the input bit buffer is in use.
References getNumBits(), KTL_ASSERT, num_bits_in_input_buffer_, popBit(), and stream_data_.
Referenced by kazoo::Deframer::findFrameStart(), popByte(), kazoo::SymbolStream< Token_t >::processBinaryStream(), and TEST().
popByte()
bool kazoo::BinaryStream::popByte (uint8_t & output) inline
References popBits().
Referenced by kazoo::Deframer::findFrameData(), kazoo::Deframer::findFrameEnd(), and kazoo::Deframer::findFrameSize().
addBytes()
void kazoo::BinaryStream::addBytes (std::span< const uint8_t > input_bytes) inline
Add bytes to the stream. If the stream is not byte aligned when this function is called, an exception will be thrown.
Parameters
input_bits - The bits to be added to the stream,
References isByteAligned(), and stream_data_.
Referenced by kazoo::TranslationLayer::addData(), kazoo::ModelTester::helper_encodeStringToAudioChannel(), TEST(), and kazoo::ModelTester::test_basicEncodeDecode().
getNumBits()
size_t kazoo::BinaryStream::getNumBits () const inline
Get the number of bits in the stream.
Returns
The number of bits in the stream.
References getInputBitBufferSpace(), getOutputBitBufferUsedBits(), and stream_data_.
Referenced by kazoo::TranslationLayer::addData(), popBits(), and TEST().
getNumBytes()
size_t kazoo::BinaryStream::getNumBytes () const inline
Get the number of bytes in the stream. If the stream has spare bits that do not align to a byte, the number of bytes will be rounded up to the nearest byte.
Returns
The number of bytes in the stream.
References stream_data_.
Referenced by kazoo::Deframer::findFrameData(), kazoo::Deframer::findFrameEnd(), kazoo::Deframer::findFrameSize(), kazoo::Deframer::findFrameStart(), kazoo::TranslationLayer::listeningThreadFunc(), kazoo::TranslationLayer::loadAndDecodeWav(), kazoo::SymbolStream< Token_t >::processBinaryStream(), and TEST().
isByteAligned()
bool kazoo::BinaryStream::isByteAligned () const inline
Get the byte alignment status of the stream.
Returns
true if the stream is byte aligned, false otherwise.
References num_bits_in_input_buffer_, and num_bits_used_in_output_buffer_.
Referenced by addBytes(), getOutputBitBufferUsedBits(), kazoo::TranslationLayer::listeningThreadFunc(), kazoo::TranslationLayer::loadAndDecodeWav(), pad(), kazoo::SymbolStream< Token_t >::processBinaryStream(), and TEST().
getInputBitBufferSpace()
size_t kazoo::BinaryStream::getInputBitBufferSpace () const inline
If adding bits, this will return the number of bits that can be added to the stream before the stream is byte aligned.
Returns
The number of missing bits to align the stream to a byte.
References num_bits_in_input_buffer_.
Referenced by getNumBits(), operator<<(), and TEST().
getOutputBitBufferUsedBits()
size_t kazoo::BinaryStream::getOutputBitBufferUsedBits () const inline
References isByteAligned(), and num_bits_used_in_output_buffer_.
Referenced by getNumBits().
getBytes()
std::vector< uint8_t > kazoo::BinaryStream::getBytes (size_t num_bytes) inline
Get the next num_bytes bytes from the stream. Does not remove the bytes from the stream.
Parameters
num_bytes - The number of bytes to get
Returns
A vector copy of the next num_bytes bytes from the stream.
References stream_data_.
Referenced by kazoo::TranslationLayer::loadAndDecodeWav(), and TEST().
getStreamDataConst()
const std::deque< uint8_t > & kazoo::BinaryStream::getStreamDataConst () const inline
Get a const reference to the underlying stream data.
Returns
A const reference to the underlying stream data.
References stream_data_.
Referenced by kazoo::ModelTester::helper_decodeAudioChannelToString(), operator<<(), kazoo::Deframer::printFrameData(), TEST(), and kazoo::ModelTester::test_basicEncodeDecode().
pad()
void kazoo::BinaryStream::pad () inline
If the last element is being used as a bit buffer, this will fill the remaining bits until the stream is byte aligned.
artifically
References addBit(), isByteAligned(), KTL_ASSERT, and num_bits_used_in_output_buffer_.
Referenced by kazoo::TranslationLayer::listeningThreadFunc(), kazoo::TranslationLayer::loadAndDecodeWav(), and TEST().
clear()
void kazoo::BinaryStream::clear () inline
Clear the stream data.
References num_bits_in_input_buffer_, num_bits_used_in_output_buffer_, and stream_data_.
Member Data Documentation
stream_data_
std::deque<uint8_t> kazoo::BinaryStream::stream_data_ {} private
Referenced by addBit(), addBytes(), clear(), getBytes(), getNumBits(), getNumBytes(), getStreamDataConst(), popBit(), and popBits().
num_bits_in_input_buffer_
size_t kazoo::BinaryStream::num_bits_in_input_buffer_ {0} private
The number of bits in the 'bit input buffer'. If a user calls addBits(0bXx, num_bits), the buffer, which is the last byte in stream_date_, this variable will be the number of bits in that buffer. If it does not equal 0, then the stream is not byte aligned. Bits have to be added or pad() has to be called prior to other actions.
Referenced by addBit(), clear(), getInputBitBufferSpace(), isByteAligned(), popBit(), and popBits().
num_bits_used_in_output_buffer_
size_t kazoo::BinaryStream::num_bits_used_in_output_buffer_ {0} private
Same deal as above, but for the output buffer. This can only be allowed to be non-zero if the input buffer is zero. This is to be used in the getBits() method.
Referenced by addBit(), clear(), getOutputBitBufferUsedBits(), isByteAligned(), pad(), and popBit().
The documentation for this class was generated from the following file:
binary_stream.hpp