Kazooformation: kazoo::model::K3ReasonableModel::K3Model Class Reference
kazoo::model::K3ReasonableModel::K3Model Class Reference final
#include <k3_model.hpp>
Public Types
using TokenValueMap = std::map< Token, uint32_t >
Maps a token to it's corresponding binary value.
Public Member Functions
K3Model ()
void decodeAudioToSymbols (const IAudioChannel &audio_channel, ISymbolStream &symbol_stream) const override
void encodeSymbol (EncoderContext &context, uint32_t token_id, IAudioChannel &audio_channel) const override
uint32_t getNumSamplesPerSymbol () const override
virtual uint32_t getSymbolBitMask () const
size_t getSymbolBitWidth () const override
uint32_t getSymbolId (uint32_t value) const override
Token getToken (uint32_t value) const
uint32_t getValue (uint32_t token_id) const override
Get the value corresponding to the numeric token id.
Private Member Functions
Token detectSymbolFromFftResults (const Fft::FftResults &results) const
Private Attributes
const uint32_t symbol_bit_width_
const TokenValueMap token_values_
Member Typedef Documentation
TokenValueMap
using kazoo::SymbolModel< Token >::TokenValueMap = std::map<Token , uint32_t> inherited
Maps a token to it's corresponding binary value.
Constructor & Destructor Documentation
K3Model()
kazoo::model::K3ReasonableModel::K3Model::K3Model () inline
References kazoo::model::K3ReasonableModel::SYMBOL_0, kazoo::model::K3ReasonableModel::SYMBOL_1, and kazoo::model::K3ReasonableModel::SYMBOL_BIT_WIDTH.
Member Function Documentation
encodeSymbol()
void kazoo::model::K3ReasonableModel::K3Model::encodeSymbol (EncoderContext & context, uint32_t token_id, IAudioChannel & audio_channel) const inline override virtual
Implements kazoo::ISymbolModel.
References kazoo::IAudioChannel::addSample(), kazoo::pcm_data::K3_DOOT_HIGH, kazoo::pcm_data::K3_DOOT_LOW, KTL_ASSERT, kazoo::model::K3ReasonableModel::SYMBOL_0, and kazoo::model::K3ReasonableModel::SYMBOL_1.
decodeAudioToSymbols()
void kazoo::model::K3ReasonableModel::K3Model::decodeAudioToSymbols (const IAudioChannel & audio_channel, ISymbolStream & symbol_stream) const inline override virtual
Todo:
where did these magic numbers come from????
Todo:
magic number/parameterize
Implements kazoo::ISymbolModel.
References kazoo::ISymbolStream::addSymbolId(), kazoo::Fft::FftResults::FreqAmp::amplitude, kazoo::Fft::FftResults::average_amplitude, detectSymbolFromFftResults(), kazoo::Fft::FftResults::FreqAmp::frequency, kazoo::IAudioChannel::getSamplesRef(), kazoo::Fft::FftResults::max_amplitude, kazoo::Fft::FftResults::normalized_amplitude_std_dev, kazoo::Fft::FftResults::normalized_amplitude_variance, kazoo::Fft::performFftFrequency(), kazoo::model::K3ReasonableModel::SAMPLES_PER_SYMBOL, kazoo::model::K3ReasonableModel::SYMBOL_0, kazoo::model::K3ReasonableModel::SYMBOL_1, and kazoo::model::K3ReasonableModel::UNKNOWN.
Referenced by TEST_F().
getNumSamplesPerSymbol()
uint32_t kazoo::model::K3ReasonableModel::K3Model::getNumSamplesPerSymbol () const inline override virtual
Implements kazoo::ISymbolModel.
References kazoo::model::K3ReasonableModel::SAMPLES_PER_SYMBOL.
detectSymbolFromFftResults()
Token kazoo::model::K3ReasonableModel::K3Model::detectSymbolFromFftResults (const Fft::FftResults & results) const inline private
References kazoo::Fft::FftResults::getNormalizedPeaks(), kazoo::model::K3ReasonableModel::MAX_FREQ_CUT_OFF, kazoo::model::K3ReasonableModel::MIN_AMPLITUDE_CUT_OFF_PARAMETER, kazoo::model::K3ReasonableModel::MIN_FREQ_CUT_OFF, kazoo::model::K3ReasonableModel::NUM_PEAK_FREQS_TO_CHECK, kazoo::model::K3ReasonableModel::PEAK_OF_INTEREST_ENVELOPE_HZ, kazoo::model::K3ReasonableModel::SYM_A_00_PEAKS_OF_INTEREST, kazoo::model::K3ReasonableModel::SYM_D_01_PEAKS_OF_INTEREST, kazoo::model::K3ReasonableModel::SYMBOL_0, kazoo::model::K3ReasonableModel::SYMBOL_1, and kazoo::model::K3ReasonableModel::UNKNOWN.
Referenced by decodeAudioToSymbols().
getSymbolBitWidth()
size_t kazoo::SymbolModel< Token >::getSymbolBitWidth () const inline override virtual inherited
Implements kazoo::ISymbolModel.
getValue()
uint32_t kazoo::SymbolModel< Token >::getValue (uint32_t token_id) const inline override virtual inherited
Get the value corresponding to the numeric token id.
Parameters
token_id - The Token_t cast to an unsigned integer.
Returns
uint32_t - The value of the token.
Implements kazoo::ISymbolModel.
getToken()
Token kazoo::SymbolModel< Token >::getToken (uint32_t value) const inline inherited
getSymbolId()
uint32_t kazoo::SymbolModel< Token >::getSymbolId (uint32_t value) const inline override virtual inherited
From a binary value, get the corresponding symbol/token id.
Todo:
Need to remove 'token' verbiage, use 'symbol.id' and 'symbol.value' instead. This is for the sake of getting rid of templated interfaces which was a mistake from 5 hours of effort ago.
Parameters
value - The binary value to convert to a token id.
Returns
uint32_t - The token id corresponding to the value.
Implements kazoo::ISymbolModel.
getSymbolBitMask()
virtual uint32_t kazoo::ISymbolModel::getSymbolBitMask () const inline virtual inherited
References kazoo::ISymbolModel::getSymbolBitWidth().
Member Data Documentation
token_values_
const TokenValueMap kazoo::SymbolModel< Token >::token_values_ private inherited
symbol_bit_width_
const uint32_t kazoo::SymbolModel< Token >::symbol_bit_width_ private inherited
The documentation for this class was generated from the following file:
k3_model.hpp