Kazooformation: sock::TcpSocketServer Class Reference
sock::TcpSocketServer Class Reference
The TCP socket server class.
#include <tcp_socket.hpp>
Public Member Functions
TcpSocketServer ()
~TcpSocketServer ()
bool accept (sock::TcpSocketServer &new_socket)
bool bind (const int port)
bool close ()
bool create ()
std::string getClientAddress () const
bool init (int port_number)
bool isValid () const
bool listen () const
bool receive (std::string &data) const
bool send (const std::string &data) const
bool sendRawData (const uint8_t *data, size_t size)
Private Attributes
sockaddr_in addr_ = {}
int sock_ = -1
Detailed Description
The TCP socket server class.
Constructor & Destructor Documentation
TcpSocketServer()
sock::TcpSocketServer::TcpSocketServer () inline
References addr_.
~TcpSocketServer()
sock::TcpSocketServer::~TcpSocketServer () inline
References close(), isValid(), and sock_.
Member Function Documentation
init()
bool sock::TcpSocketServer::init (int port_number) inline
References bind(), create(), listen(), and sock_.
Referenced by httpServerThread().
create()
bool sock::TcpSocketServer::create () inline
References isValid(), and sock_.
Referenced by init().
bind()
bool sock::TcpSocketServer::bind (const int port) inline
References addr_, bind(), isValid(), and sock_.
Referenced by bind(), and init().
listen()
bool sock::TcpSocketServer::listen () const inline
References isValid(), sock::K_MAX_CONNECTIONS, listen(), and sock_.
Referenced by init(), and listen().
accept()
bool sock::TcpSocketServer::accept (sock::TcpSocketServer & new_socket) inline
References accept(), addr_, and sock_.
Referenced by accept(), and httpServerThread().
close()
bool sock::TcpSocketServer::close () inline
References close(), isValid(), and sock_.
Referenced by ~TcpSocketServer(), and close().
send()
bool sock::TcpSocketServer::send (const std::string & data) const inline
References send(), and sock_.
Referenced by httpServerThread(), send(), and sendRawData().
sendRawData()
bool sock::TcpSocketServer::sendRawData (const uint8_t * data, size_t size) inline
Todo:
spanify, no need to use pointers here
References send(), and sock_.
receive()
bool sock::TcpSocketServer::receive (std::string & data) const inline
References sock::K_MAX_RECEIVE, and sock_.
Referenced by httpServerThread().
isValid()
bool sock::TcpSocketServer::isValid () const inline
References sock_.
Referenced by ~TcpSocketServer(), bind(), close(), create(), and listen().
getClientAddress()
std::string sock::TcpSocketServer::getClientAddress () const inline
References addr_.
Member Data Documentation
sock_
int sock::TcpSocketServer::sock_ = -1 private
Referenced by ~TcpSocketServer(), accept(), bind(), close(), create(), init(), isValid(), listen(), receive(), send(), and sendRawData().
addr_
sockaddr_in sock::TcpSocketServer::addr_ = {} private
Referenced by TcpSocketServer(), accept(), bind(), and getClientAddress().
The documentation for this class was generated from the following file:
tcp_socket.hpp