Kazooformation: kazoo::ModelTester Class Reference
kazoo::ModelTester Class Reference
#include <model_tester.hpp>
Public Member Functions
ModelTester (kazoo::ISymbolModel &symbol_model, kazoo::ISymbolStream &symbol_stream, kazoo::IEncoder &encoder)
double getScore ()
void resetState ()
void runAllTests ()
Protected Member Functions
void logDebug (const std::string &message)
void logError (const std::string &message)
void logInfo (const std::string &message)
void logWarning (const std::string &message)
Private Member Functions
bool expectTrue (bool condition, std::string_view on_fail_message, double penalty_on_fail=1.0, double score_increase_on_pass=0.1)
std::string getRandomTestString ()
bool helper_decodeAudioChannelToString (const kazoo::AudioChannel &audio_channel, std::string &decoded_string)
bool helper_encodeStringToAudioChannel (const std::string &test_string, kazoo::AudioChannel &audio_channel)
void log (const std::string &level, const std::string &message)
bool test_basicEncodeDecode ()
bool test_gaussianNoiseTolerance ()
Static Private Member Functions
static double getRandomDouble (double min, double max)
Private Attributes
kazoo::IEncoder & encoder_
std::string logger_name_
double score_ = 0.0
kazoo::ISymbolModel & symbol_model_
kazoo::ISymbolStream & symbol_stream_
const std::array< std::string_view, 5 > test_strings_
Constructor & Destructor Documentation
ModelTester()
kazoo::ModelTester::ModelTester (kazoo::ISymbolModel & symbol_model, kazoo::ISymbolStream & symbol_stream, kazoo::IEncoder & encoder) inline
Member Function Documentation
runAllTests()
void kazoo::ModelTester::runAllTests ()
References kazoo::Logger::logDebug(), resetState(), score_, test_basicEncodeDecode(), and test_gaussianNoiseTolerance().
getScore()
double kazoo::ModelTester::getScore () inline
References score_.
resetState()
void kazoo::ModelTester::resetState () inline
References kazoo::IEncoder::clear(), kazoo::ISymbolStream::clear(), encoder_, and symbol_stream_.
Referenced by runAllTests(), and test_gaussianNoiseTolerance().
getRandomDouble()
double kazoo::ModelTester::getRandomDouble (double min, double max) static private
Referenced by getRandomTestString().
getRandomTestString()
std::string kazoo::ModelTester::getRandomTestString () private
References getRandomDouble(), and test_strings_.
Referenced by test_gaussianNoiseTolerance().
expectTrue()
bool kazoo::ModelTester::expectTrue (bool condition, std::string_view on_fail_message, double penalty_on_fail = 1.0, double score_increase_on_pass = 0.1) private
References kazoo::Logger::logError(), and score_.
Referenced by helper_encodeStringToAudioChannel(), test_basicEncodeDecode(), and test_gaussianNoiseTolerance().
helper_encodeStringToAudioChannel()
bool kazoo::ModelTester::helper_encodeStringToAudioChannel (const std::string & test_string, kazoo::AudioChannel & audio_channel) private
References kazoo::BinaryStream::addBytes(), kazoo::IEncoder::encodeAvailableSymbols(), encoder_, expectTrue(), kazoo::ISymbolStream::getNumBytes(), kazoo::AudioChannel::getNumSamples(), kazoo::ISymbolModel::getSymbolBitWidth(), kazoo::ISymbolStream::processBinaryStream(), symbol_model_, and symbol_stream_.
Referenced by test_gaussianNoiseTolerance().
helper_decodeAudioChannelToString()
bool kazoo::ModelTester::helper_decodeAudioChannelToString (const kazoo::AudioChannel & audio_channel, std::string & decoded_string) private
References kazoo::ISymbolStream::clear(), kazoo::ISymbolModel::decodeAudioToSymbols(), kazoo::BinaryStream::getStreamDataConst(), kazoo::ISymbolStream::populateBinaryStream(), symbol_model_, and symbol_stream_.
Referenced by test_gaussianNoiseTolerance().
test_basicEncodeDecode()
bool kazoo::ModelTester::test_basicEncodeDecode () private
References kazoo::BinaryStream::addBytes(), kazoo::ISymbolStream::clear(), kazoo::ISymbolModel::decodeAudioToSymbols(), kazoo::IEncoder::encodeAvailableSymbols(), encoder_, expectTrue(), kazoo::ISymbolStream::getNumBytes(), kazoo::AudioChannel::getNumSamples(), kazoo::BinaryStream::getStreamDataConst(), kazoo::ISymbolModel::getSymbolBitWidth(), kazoo::Logger::logDebug(), kazoo::ISymbolStream::populateBinaryStream(), kazoo::ISymbolStream::processBinaryStream(), symbol_model_, and symbol_stream_.
Referenced by runAllTests().
test_gaussianNoiseTolerance()
bool kazoo::ModelTester::test_gaussianNoiseTolerance () private
References expectTrue(), getRandomTestString(), helper_decodeAudioChannelToString(), helper_encodeStringToAudioChannel(), kazoo::Logger::logDebug(), and resetState().
Referenced by runAllTests().
logWarning()
void kazoo::Logger::logWarning (const std::string & message) inline protected inherited
References kazoo::Logger::log().
logError()
void kazoo::Logger::logError (const std::string & message) inline protected inherited
References kazoo::Logger::log().
Referenced by expectTrue().
logInfo()
void kazoo::Logger::logInfo (const std::string & message) inline protected inherited
References kazoo::Logger::log().
logDebug()
void kazoo::Logger::logDebug (const std::string & message) inline protected inherited
References kazoo::Logger::log().
Referenced by runAllTests(), test_basicEncodeDecode(), and test_gaussianNoiseTolerance().
log()
void kazoo::Logger::log (const std::string & level, const std::string & message) inline private inherited
References kazoo::Logger::logger_name_.
Referenced by kazoo::Logger::logDebug(), kazoo::Logger::logError(), kazoo::Logger::logInfo(), and kazoo::Logger::logWarning().
Member Data Documentation
test_strings_
const std::array<std::string_view, 5> kazoo::ModelTester::test_strings_ private
Initial value:
{"t", "Hello, World!", "test1",
                                                      "Longer Testing String", "abd"}
Referenced by getRandomTestString().
score_
double kazoo::ModelTester::score_ = 0.0 private
Referenced by expectTrue(), getScore(), and runAllTests().
symbol_model_
kazoo::ISymbolModel& kazoo::ModelTester::symbol_model_ private
Referenced by helper_decodeAudioChannelToString(), helper_encodeStringToAudioChannel(), and test_basicEncodeDecode().
symbol_stream_
kazoo::ISymbolStream& kazoo::ModelTester::symbol_stream_ private
Referenced by helper_decodeAudioChannelToString(), helper_encodeStringToAudioChannel(), resetState(), and test_basicEncodeDecode().
encoder_
kazoo::IEncoder& kazoo::ModelTester::encoder_ private
Referenced by helper_encodeStringToAudioChannel(), resetState(), and test_basicEncodeDecode().
logger_name_
std::string kazoo::Logger::logger_name_ private inherited
Referenced by kazoo::Logger::log().
The documentation for this class was generated from the following files:
model_tester.hpp
model_tester.cpp