Kazooformation: kazoo::ISymbolModel Class Reference
kazoo::ISymbolModel Class Reference abstract
#include <symbol_model.hpp>
Public Member Functions
virtual ~ISymbolModel ()=default
virtual void decodeAudioToSymbols (const IAudioChannel &audio_channel, ISymbolStream &symbol_stream) const =0
virtual void encodeSymbol (EncoderContext &context, uint32_t token_id, IAudioChannel &audio_channel) const =0
virtual uint32_t getNumSamplesPerSymbol () const =0
virtual uint32_t getSymbolBitMask () const
virtual size_t getSymbolBitWidth () const =0
virtual uint32_t getSymbolId (uint32_t value) const =0
virtual uint32_t getValue (uint32_t token_id) const =0
Get the value corresponding to the numeric token id.
Constructor & Destructor Documentation
~ISymbolModel()
virtual kazoo::ISymbolModel::~ISymbolModel () virtual default
Member Function Documentation
getSymbolBitWidth()
virtual size_t kazoo::ISymbolModel::getSymbolBitWidth () const pure virtual
Implemented in kazoo::SymbolModel< Token_t >, and kazoo::SymbolModel< Token >.
Referenced by kazoo::SymbolStream< Token_t >::getNumBits(), getSymbolBitMask(), kazoo::ModelTester::helper_encodeStringToAudioChannel(), kazoo::SymbolStream< Token_t >::populateBinaryStream(), kazoo::SymbolStream< Token_t >::processBinaryStream(), and kazoo::ModelTester::test_basicEncodeDecode().
getSymbolBitMask()
virtual uint32_t kazoo::ISymbolModel::getSymbolBitMask () const inline virtual
References getSymbolBitWidth().
getValue()
virtual uint32_t kazoo::ISymbolModel::getValue (uint32_t token_id) const pure virtual
Get the value corresponding to the numeric token id.
Parameters
token_id - The Token_t cast to an unsigned integer.
Returns
uint32_t - The value of the token.
Implemented in kazoo::SymbolModel< Token_t >, and kazoo::SymbolModel< Token >.
Referenced by kazoo::SymbolStream< Token_t >::populateBinaryStream().
getSymbolId()
virtual uint32_t kazoo::ISymbolModel::getSymbolId (uint32_t value) const pure virtual
From a binary value, get the corresponding symbol/token id.
Todo:
Need to remove 'token' verbiage, use 'symbol.id' and 'symbol.value' instead. This is for the sake of getting rid of templated interfaces which was a mistake from 5 hours of effort ago.
Parameters
value - The binary value to convert to a token id.
Returns
uint32_t - The token id corresponding to the value.
Implemented in kazoo::SymbolModel< Token_t >, and kazoo::SymbolModel< Token >.
Referenced by kazoo::SymbolStream< Token_t >::processBinaryStream().
encodeSymbol()
virtual void kazoo::ISymbolModel::encodeSymbol (EncoderContext & context, uint32_t token_id, IAudioChannel & audio_channel) const pure virtual
Implemented in kazoo::model::K1Model::Model, kazoo::model::K2PeakModel::Model, kazoo::model::K3ReasonableModel::K3Model, kazoo::SymbolModel< Token_t >, kazoo::SymbolModel< Token >, and kazoo::model::Testing::Model.
Referenced by kazoo::Encoder< Token_t >::encodeAvailableSymbols().
decodeAudioToSymbols()
virtual void kazoo::ISymbolModel::decodeAudioToSymbols (const IAudioChannel & audio_channel, ISymbolStream & symbol_stream) const pure virtual
Implemented in kazoo::model::K1Model::Model, kazoo::model::K2PeakModel::Model, kazoo::model::K3ReasonableModel::K3Model, kazoo::SymbolModel< Token_t >, kazoo::SymbolModel< Token >, and kazoo::model::Testing::Model.
Referenced by kazoo::ModelTester::helper_decodeAudioChannelToString(), kazoo::TranslationLayer::listeningThreadFunc(), kazoo::TranslationLayer::loadAndDecodeWav(), and kazoo::ModelTester::test_basicEncodeDecode().
getNumSamplesPerSymbol()
virtual uint32_t kazoo::ISymbolModel::getNumSamplesPerSymbol () const pure virtual
Implemented in kazoo::model::K1Model::Model, kazoo::model::K2PeakModel::Model, kazoo::model::K3ReasonableModel::K3Model, kazoo::SymbolModel< Token_t >, and kazoo::SymbolModel< Token >.
The documentation for this class was generated from the following file:
symbol_model.hpp