Kazooformation: kazoo::WaveTools Class Reference
kazoo::WaveTools Class Reference
#include <wave_tools.hpp>
Static Public Member Functions
static void addGaussianNoise (IAudioChannel &channel, const double mean, const double std_deviation, const size_t num_samples)
static constexpr double generateSinWaveSamples (IAudioChannel &channel, const double frequency, const size_t num_samples, const double amplitude=1.0, const double starting_angle_radians=0.0)
Add a sine wave to the audio channel.
Member Function Documentation
generateSinWaveSamples()
static constexpr double kazoo::WaveTools::generateSinWaveSamples (IAudioChannel & channel, const double frequency, const size_t num_samples, const double amplitude = 1.0, const double starting_angle_radians = 0.0) inline static constexpr
Add a sine wave to the audio channel.
Parameters
channel - The audio channel to add the sine wave to.
frequency - The frequency of the sine wave in Hz.
num_samples - The number of samples to generate.
amplitude - The amplitude of the sine wave, 0.0 to 1.0. Default is 1.0.
starting_angle_radians - The starting angle of the sine wave in radians.
Returns
The ending angle of the sine wave in radians.
References kazoo::IAudioChannel::addSample(), kazoo::AUDIO_SAMPLE_RATE, and kazoo::MAX_SAMPLE_AMPLITUDE.
Referenced by kazoo::model::Testing::Model::encodeSymbol(), and TEST().
addGaussianNoise()
static void kazoo::WaveTools::addGaussianNoise (IAudioChannel & channel, const double mean, const double std_deviation, const size_t num_samples) inline static
References kazoo::IAudioChannel::addSample(), and kazoo::MAX_SAMPLE_AMPLITUDE.
Referenced by TEST(), and TEST_F().
The documentation for this class was generated from the following file:
wave_tools.hpp