Kazooformation: kazoo::IEncoder Class Reference
kazoo::IEncoder Class Reference abstract
#include <encoder.hpp>
Public Member Functions
virtual ~IEncoder ()=default
virtual void clear ()=0
virtual size_t encodeAvailableSymbols (ISymbolStream &symbol_stream, IAudioChannel &audio_channel, bool pre_post_padding=false)=0
Constructor & Destructor Documentation
~IEncoder()
virtual kazoo::IEncoder::~IEncoder () virtual default
Member Function Documentation
clear()
virtual void kazoo::IEncoder::clear () pure virtual
Implemented in kazoo::Encoder< Token_t >, and kazoo::Encoder< Token >.
Referenced by kazoo::ModelTester::resetState().
encodeAvailableSymbols()
virtual size_t kazoo::IEncoder::encodeAvailableSymbols (ISymbolStream & symbol_stream, IAudioChannel & audio_channel, bool pre_post_padding = false) pure virtual
Implemented in kazoo::Encoder< Token_t >, and kazoo::Encoder< Token >.
Referenced by kazoo::ModelTester::helper_encodeStringToAudioChannel(), and kazoo::ModelTester::test_basicEncodeDecode().
The documentation for this class was generated from the following file:
encoder.hpp