Kazooformation: kazoo::IAudioChannel Class Reference
kazoo::IAudioChannel Class Reference abstract
#include <audio_channel.hpp>
Public Types
using Sample = int16_t
Public Member Functions
virtual ~IAudioChannel ()=default
virtual void addSample (int16_t sample)=0
virtual void clear ()=0
virtual const std::span< const Sample > getSamplesRef () const =0
Member Typedef Documentation
Sample
using kazoo::IAudioChannel::Sample = int16_t
Constructor & Destructor Documentation
~IAudioChannel()
virtual kazoo::IAudioChannel::~IAudioChannel () virtual default
Member Function Documentation
addSample()
virtual void kazoo::IAudioChannel::addSample (int16_t sample) pure virtual
Implemented in kazoo::AudioChannel, and kazoo::WavFile.
Referenced by kazoo::WaveTools::addGaussianNoise(), kazoo::model::K1Model::Model::encodeSymbol(), kazoo::model::K2PeakModel::Model::encodeSymbol(), kazoo::model::K3ReasonableModel::K3Model::encodeSymbol(), kazoo::WaveTools::generateSinWaveSamples(), and kazoo::WavFile::populateAudioChannel().
getSamplesRef()
virtual const std::span< const Sample > kazoo::IAudioChannel::getSamplesRef () const pure virtual
Implemented in kazoo::AudioChannel, and kazoo::WavFile.
Referenced by kazoo::model::K1Model::Model::decodeAudioToSymbols(), kazoo::model::K2PeakModel::Model::decodeAudioToSymbols(), kazoo::model::K3ReasonableModel::K3Model::decodeAudioToSymbols(), kazoo::model::Testing::Model::decodeAudioToSymbols(), kazoo::WavFile::loadFromAudioChannel(), and kazoo::PulseAudio::Player::play().
clear()
virtual void kazoo::IAudioChannel::clear () pure virtual
Implemented in kazoo::AudioChannel, and kazoo::WavFile.
The documentation for this class was generated from the following file:
audio_channel.hpp