Kazooformation: kazoo::Encoder< Token_t > Class Template Reference
kazoo::Encoder< Token_t > Class Template Reference
#include <encoder.hpp>
Public Member Functions
Encoder (const ISymbolModel &symbol_model)
void clear () override
size_t encodeAvailableSymbols (ISymbolStream &symbol_stream, IAudioChannel &audio_channel, bool pre_post_padding=false) override
Pops symbols from the front of the symbol stream and encodes them into the audio buffer.
Private Member Functions
void encodePreamble (IAudioChannel &audio_channel)
Adds a preamble to the audio channel to help with synchronization.
void encodeTail (IAudioChannel &audio_channel)
Private Attributes
EncoderContext context_
const ISymbolModel & symbol_model_
Constructor & Destructor Documentation
Encoder()
template<typename Token_t > kazoo::Encoder< Token_t >::Encoder (const ISymbolModel & symbol_model) inline
Member Function Documentation
clear()
template<typename Token_t > void kazoo::Encoder< Token_t >::clear () inline override virtual
Implements kazoo::IEncoder.
References kazoo::Encoder< Token_t >::context_.
encodeAvailableSymbols()
template<typename Token_t > size_t kazoo::Encoder< Token_t >::encodeAvailableSymbols (ISymbolStream & symbol_stream, IAudioChannel & audio_channel, bool pre_post_padding = false) inline override virtual
Pops symbols from the front of the symbol stream and encodes them into the audio buffer.
Parameters
symbol_stream - The symbol stream to pop symbols off of.
[out] audio_channel - The audio channel to populate
pre_post_padding - If true, the encoder will add padding before and after the symbols to help with synchronization.
Returns
The number of symbols that were added.
Implements kazoo::IEncoder.
References kazoo::Encoder< Token_t >::context_, kazoo::Encoder< Token_t >::encodePreamble(), kazoo::ISymbolModel::encodeSymbol(), kazoo::Encoder< Token_t >::encodeTail(), kazoo::ISymbolStream::popSymbolTokenId(), and kazoo::Encoder< Token_t >::symbol_model_.
Referenced by kazoo::TranslationLayer::encode().
encodePreamble()
template<typename Token_t > void kazoo::Encoder< Token_t >::encodePreamble (IAudioChannel & audio_channel) inline private
Adds a preamble to the audio channel to help with synchronization.
Parameters
audio_channel - The audio channel to add the preamble to.
Referenced by kazoo::Encoder< Token_t >::encodeAvailableSymbols().
encodeTail()
template<typename Token_t > void kazoo::Encoder< Token_t >::encodeTail (IAudioChannel & audio_channel) inline private
Todo:
This was done somewhere else. It should be defined at the model level.
Referenced by kazoo::Encoder< Token_t >::encodeAvailableSymbols().
Member Data Documentation
context_
template<typename Token_t > EncoderContext kazoo::Encoder< Token_t >::context_ private
Referenced by kazoo::Encoder< Token_t >::clear(), and kazoo::Encoder< Token_t >::encodeAvailableSymbols().
symbol_model_
template<typename Token_t > const ISymbolModel& kazoo::Encoder< Token_t >::symbol_model_ private
Referenced by kazoo::Encoder< Token_t >::encodeAvailableSymbols().
The documentation for this class was generated from the following file:
encoder.hpp