Kazooformation: kazoo::PulseAudio::Player Class Reference
kazoo::PulseAudio::Player Class Reference
#include <pulse_audio.hpp>
Public Member Functions
Player ()=delete
Static Public Member Functions
static void play (const IAudioChannel &channel)
Detailed Description
[https://github.com/joshua-jerred/SignalEasel/blob/main/src/pulse_audio_writer.cpp]
Todo:
refactor
Constructor & Destructor Documentation
Player()
kazoo::PulseAudio::Player::Player () delete
Member Function Documentation
play()
static void kazoo::PulseAudio::Player::play (const IAudioChannel & channel) inline static
References kazoo::IAudioChannel::getSamplesRef(), KTL_ASSERT, kazoo::PulseAudio::PULSE_AUDIO_APP_NAME, and kazoo::PulseAudio::PULSE_AUDIO_SAMPLE_SPEC.
Referenced by kazoo::TranslationLayer::playAudioBlocking(), and TEST().
The documentation for this class was generated from the following file:
pulse_audio.hpp