Kazooformation: kazoo::AudioChannel Class Reference
kazoo::AudioChannel Class Reference
#include <audio_channel.hpp>
Public Types
using Sample = int16_t
Public Member Functions
AudioChannel ()=default
void addSample (const Sample sample) override
void addSamples (std::span< const Sample > samples)
void clear () override
uint32_t getLengthMs () const
size_t getNumSamples () const
Sample getSample (size_t index) const
const std::span< const Sample > getSamplesRef () const override
void setSample (size_t index, Sample sample)
Protected Attributes
std::vector< Sample > samples_ {}
Member Typedef Documentation
Sample
using kazoo::IAudioChannel::Sample = int16_t inherited
Constructor & Destructor Documentation
AudioChannel()
kazoo::AudioChannel::AudioChannel () default
Member Function Documentation
addSample()
void kazoo::AudioChannel::addSample (const Sample sample) inline override virtual
Implements kazoo::IAudioChannel.
References samples_.
Referenced by TEST().
addSamples()
void kazoo::AudioChannel::addSamples (std::span< const Sample > samples) inline
References samples_.
Referenced by kazoo::TranslationLayer::listeningThreadFunc().
getNumSamples()
size_t kazoo::AudioChannel::getNumSamples () const inline
References samples_.
Referenced by kazoo::TranslationLayer::encode(), kazoo::ModelTester::helper_encodeStringToAudioChannel(), kazoo::TranslationLayer::listeningThreadFunc(), TEST(), kazoo::ModelTester::test_basicEncodeDecode(), and TEST_F().
getSamplesRef()
const std::span< const Sample > kazoo::AudioChannel::getSamplesRef () const inline override virtual
Implements kazoo::IAudioChannel.
References samples_.
clear()
void kazoo::AudioChannel::clear () inline override virtual
Implements kazoo::IAudioChannel.
References samples_.
Referenced by kazoo::TranslationLayer::listeningThreadFunc(), kazoo::TranslationLayer::playAudioBlocking(), and kazoo::TranslationLayer::sendFrame().
getLengthMs()
uint32_t kazoo::AudioChannel::getLengthMs () const inline
References samples_.
getSample()
Sample kazoo::AudioChannel::getSample (size_t index) const inline
References KTL_ASSERT, and samples_.
setSample()
void kazoo::AudioChannel::setSample (size_t index, Sample sample) inline
References KTL_ASSERT, and samples_.
Member Data Documentation
samples_
std::vector<Sample> kazoo::AudioChannel::samples_ {} protected
Referenced by addSample(), addSamples(), clear(), getLengthMs(), getNumSamples(), getSample(), getSamplesRef(), and setSample().
The documentation for this class was generated from the following file:
audio_channel.hpp