Kazooformation: kazoo::Fft Class Reference
kazoo::Fft Class Reference
[https://stackoverflow.com/a/22059819]
#include <fft.hpp>
Classes
struct FftResults
Public Member Functions
Fft ()=default
Static Public Member Functions
static void performFftFrequency (const std::span< const int16_t > input, FftResults &results, uint32_t fixed_fft_bins=0, double min_fft_freq=0.0, double max_fft_freq=20 '000.0)
static void prepareCosWave (std::span< fftw_complex > in)
Detailed Description
[https://stackoverflow.com/a/22059819]
Constructor & Destructor Documentation
Fft()
kazoo::Fft::Fft () default
Member Function Documentation
performFftFrequency()
static void kazoo::Fft::performFftFrequency (const std::span< const int16_t > input, FftResults & results, uint32_t fixed_fft_bins = 0, double min_fft_freq = 0.0, double max_fft_freq = 20'000.0) inline static
Todo:
FFT without floating point?
Parameters
input - A span in PCM format. (16-bit signed integers, AUDIO_SAMPLE_RATE)
References kazoo::AUDIO_SAMPLE_RATE, kazoo::Fft::FftResults::average_amplitude, kazoo::Fft::FftResults::frequency_amplitude, KTL_ASSERT, kazoo::Fft::FftResults::max_amplitude, kazoo::Fft::FftResults::max_amplitude_index, kazoo::Fft::FftResults::normalized_amplitude_std_dev, kazoo::Fft::FftResults::normalized_amplitude_variance, kazoo::Fft::FftResults::normalized_frequency_amplitude, and kazoo::Fft::FftResults::reset().
Referenced by kazoo::model::K1Model::Model::decodeAudioToSymbols(), kazoo::model::K2PeakModel::Model::decodeAudioToSymbols(), kazoo::model::K3ReasonableModel::K3Model::decodeAudioToSymbols(), kazoo::model::Testing::Model::decodeAudioToSymbols(), and TEST().
prepareCosWave()
static void kazoo::Fft::prepareCosWave (std::span< fftw_complex > in) inline static
The documentation for this class was generated from the following file:
fft.hpp