Kazooformation: kazoo::WavFile Class Reference
kazoo::WavFile Class Reference
A class for reading and writing WAV files. [https://github.com/joshua-jerred/WavGen].
#include <wav_file.hpp>
Classes
struct DataChunk
struct FormatChunk
struct WavHeader
Public Types
using Sample = int16_t
Public Member Functions
WavFile ()=default
void addSample (int16_t sample) override
void clear () override
uint32_t getDurationMilliseconds () const
double getDurationSeconds () const
const WavHeader & getHeader () const
Get a reference to the header object.
size_t getNumSamples () const
const std::span< const int16_t > getSamplesRef () const override
void loadFromAudioChannel (IAudioChannel &audio_channel)
void populateAudioChannel (IAudioChannel &audio_channel)
void read (const std::string &file_path)
Read a WAV file from disk. Clears the current audio sample buffer.
void write (const std::string &file_path)
Static Public Attributes
static constexpr FormatChunk DEFAULT_FORMAT_CHUNK
Private Attributes
std::vector< int16_t > samples_ {}
WavHeader wav_header_ {}
double wave_angle_ = 0.0
Detailed Description
A class for reading and writing WAV files. [https://github.com/joshua-jerred/WavGen].
Member Typedef Documentation
Sample
using kazoo::IAudioChannel::Sample = int16_t inherited
Constructor & Destructor Documentation
WavFile()
kazoo::WavFile::WavFile () default
Member Function Documentation
loadFromAudioChannel()
void kazoo::WavFile::loadFromAudioChannel (IAudioChannel & audio_channel) inline
References kazoo::IAudioChannel::getSamplesRef(), and samples_.
Referenced by kazoo::TranslationLayer::saveWav(), TEST(), and TEST_F().
populateAudioChannel()
void kazoo::WavFile::populateAudioChannel (IAudioChannel & audio_channel) inline
References kazoo::IAudioChannel::addSample(), and samples_.
Referenced by kazoo::TranslationLayer::loadAndDecodeWav().
addSample()
void kazoo::WavFile::addSample (int16_t sample) inline override virtual
Implements kazoo::IAudioChannel.
References samples_.
Referenced by TEST().
read()
void kazoo::WavFile::read (const std::string & file_path) inline
Read a WAV file from disk. Clears the current audio sample buffer.
Parameters
file_path - The path to the WAV file.
References kazoo::WavFile::FormatChunk::bits_per_sample, kazoo::WavFile::FormatChunk::block_align, kazoo::WavFile::FormatChunk::byte_rate, kazoo::WavFile::WavHeader::DATA, kazoo::WavFile::WavHeader::data_chunk, kazoo::WavFile::DataChunk::data_size, kazoo::WavFile::DataChunk::data_start_position, kazoo::WavFile::FormatChunk::FMT, kazoo::WavFile::WavHeader::format_chunk, kazoo::WavFile::FormatChunk::format_chunk_size, kazoo::WavFile::FormatChunk::format_code, KTL_ASSERT, kazoo::WavFile::FormatChunk::num_channels, kazoo::WavFile::WavHeader::RIFF, kazoo::WavFile::FormatChunk::sample_rate, samples_, wav_header_, and kazoo::WavFile::WavHeader::WAVE.
Referenced by kazoo::TranslationLayer::loadAndDecodeWav(), TEST(), and TEST_F().
write()
void kazoo::WavFile::write (const std::string & file_path) inline
References kazoo::WavFile::FormatChunk::bits_per_sample, kazoo::WavFile::FormatChunk::block_align, kazoo::WavFile::FormatChunk::byte_rate, kazoo::WavFile::WavHeader::DATA, kazoo::WavFile::WavHeader::data_chunk, kazoo::WavFile::DataChunk::data_size, kazoo::WavFile::DataChunk::data_start_position, kazoo::WavFile::WavHeader::file_size, kazoo::WavFile::FormatChunk::FMT, kazoo::WavFile::WavHeader::format_chunk, kazoo::WavFile::FormatChunk::format_chunk_size, kazoo::WavFile::FormatChunk::format_code, kazoo::WavFile::WavHeader::HEADER_SIZE, kazoo::WavFile::FormatChunk::num_channels, kazoo::WavFile::WavHeader::resterToDefault(), kazoo::WavFile::FormatChunk::sample_rate, samples_, wav_header_, and kazoo::WavFile::WavHeader::WAVE.
Referenced by kazoo::TranslationLayer::saveWav(), TEST(), and TEST_F().
getHeader()
const WavHeader & kazoo::WavFile::getHeader () const inline
Get a reference to the header object.
References wav_header_.
getNumSamples()
size_t kazoo::WavFile::getNumSamples () const inline
References samples_.
Referenced by TEST(), and TEST_F().
getDurationSeconds()
double kazoo::WavFile::getDurationSeconds () const inline
References kazoo::WavFile::FormatChunk::byte_rate, kazoo::WavFile::WavHeader::data_chunk, kazoo::WavFile::DataChunk::data_size, kazoo::WavFile::WavHeader::format_chunk, and wav_header_.
Referenced by getDurationMilliseconds(), and TEST().
getDurationMilliseconds()
uint32_t kazoo::WavFile::getDurationMilliseconds () const inline
References getDurationSeconds().
Referenced by TEST().
getSamplesRef()
const std::span< const int16_t > kazoo::WavFile::getSamplesRef () const inline override virtual
Deprecated:
WaveTools
Implements kazoo::IAudioChannel.
References samples_.
Referenced by TEST().
clear()
void kazoo::WavFile::clear () inline override virtual
Implements kazoo::IAudioChannel.
References samples_.
Member Data Documentation
DEFAULT_FORMAT_CHUNK
constexpr FormatChunk kazoo::WavFile::DEFAULT_FORMAT_CHUNK static constexpr
Initial value:
= {
      .bits_per_sample = 16,
      .format_chunk_size = 16,
      .format_code = 1,
      .num_channels = 1,
      .sample_rate = 44100,
      .byte_rate = 44100 * 1 * 16 / 8,
      .block_align = 4
  }
Referenced by kazoo::WavFile::WavHeader::resterToDefault().
wav_header_
WavHeader kazoo::WavFile::wav_header_ {} private
Referenced by getDurationSeconds(), getHeader(), read(), and write().
samples_
std::vector<int16_t> kazoo::WavFile::samples_ {} private
Referenced by addSample(), clear(), getNumSamples(), getSamplesRef(), loadFromAudioChannel(), populateAudioChannel(), read(), and write().
wave_angle_
double kazoo::WavFile::wave_angle_ = 0.0 private
The documentation for this class was generated from the following file:
wav_file.hpp