Kazooformation: kazoo::TranslationLayer Class Reference
kazoo::TranslationLayer Class Reference
#include <translation_layer.hpp>
Classes
struct Stats
Public Types
enum class ModelType {
UNKNOWN = 0 , TESTING , BINARY , K1_MODEL ,
K2_PEAK_MODEL , K3_REASONABLE_MODEL
}
Public Member Functions
TranslationLayer (const ModelType model)
~TranslationLayer ()
void addData (std::span< const uint8_t > data)
Takes input data and processes it through the symbol stream.
void encode (bool pre_post_padding=false)
std::optional< KtlFrame > getReceivedFrame ()
Stats getStats ()
void loadAndDecodeWav (const std::string &filename, std::vector< uint8_t > &data)
void playAudioBlocking (bool clear_audio_channel=true)
void saveWav (const std::string &filename)
void sendFrame (const KtlFrame &frame)
void setContinuousMode (bool continuous_mode)
void startListening ()
Starts listening for audio input on the default audio device.
void stopListening ()
Private Member Functions
void listeningThreadFunc ()
Static Private Member Functions
static const ISymbolModel & getStaticSymbolModel (ModelType model_type)
Private Attributes
model::K3ReasonableModel::K3Transcoder encoder_ {model_ref_}
std::atomic< bool > is_continuous_mode_ {false}
If false then use the deframer, if true just output the bytes as ASCII as they come in.
std::atomic< bool > is_listening_ {false}
std::thread listening_thread_ {}
std::reference_wrapper< const ISymbolModel > model_ref_
const ModelType model_type_
std::queue< KtlFrame > received_frames_
std::mutex received_frames_mutex_
Stats stats_
std::mutex stats_mutex_
AudioChannel tx_audio_channel_
BinaryStream tx_binary_stream_
model::K3ReasonableModel::K3Stream tx_symbol_stream_ {model_ref_}
Static Private Attributes
static constexpr size_t FRAME_POSTAMBLE_SIZE = 2
static constexpr size_t FRAME_PREAMBLE_SIZE = 2
static constexpr double MIN_VOLUME_THRESHOLD = 0.01
The volume threshold below which pulse audio is considered quiet/not receiving audio.
Class Documentation
kazoo::TranslationLayer::Stats
struct kazoo::TranslationLayer::Stats
Class Members
size_t num_bytes
size_t num_bytes_encoded
size_t num_bytes_received
size_t symbols_last_encoded
size_t audio_samples
bool decoded_was_byte_aligned
size_t rx_audio_samples
size_t tx_audio_samples
size_t num_frames_received
uint32_t pulse_audio_latency_ms
double pulse_audio_volume
double pulse_audio_rms
bool is_quiet
Member Enumeration Documentation
ModelType
enum class kazoo::TranslationLayer::ModelType strong
Enumerator
UNKNOWN
TESTING
BINARY
K1_MODEL
K2_PEAK_MODEL
K3_REASONABLE_MODEL
Constructor & Destructor Documentation
TranslationLayer()
kazoo::TranslationLayer::TranslationLayer (const ModelType model) inline
~TranslationLayer()
kazoo::TranslationLayer::~TranslationLayer () inline
References is_listening_, and stopListening().
Member Function Documentation
getStats()
Stats kazoo::TranslationLayer::getStats () inline
References stats_, and stats_mutex_.
Referenced by main(), and TEST().
sendFrame()
void kazoo::TranslationLayer::sendFrame (const KtlFrame & frame) inline
References addData(), kazoo::AudioChannel::clear(), encode(), kazoo::KtlFrame::encodeFrame(), FRAME_POSTAMBLE_SIZE, FRAME_PREAMBLE_SIZE, playAudioBlocking(), and tx_audio_channel_.
Referenced by main(), and TEST().
addData()
void kazoo::TranslationLayer::addData (std::span< const uint8_t > data) inline
Takes input data and processes it through the symbol stream.
Parameters
data - The input data to be processed.
References kazoo::BinaryStream::addBytes(), kazoo::BinaryStream::getNumBits(), kazoo::SymbolStream< Token_t >::getNumBytes(), KTL_ASSERT, kazoo::TranslationLayer::Stats::num_bytes, kazoo::SymbolStream< Token_t >::processBinaryStream(), stats_, tx_binary_stream_, and tx_symbol_stream_.
Referenced by sendFrame(), and TEST().
encode()
void kazoo::TranslationLayer::encode (bool pre_post_padding = false)
References kazoo::TranslationLayer::Stats::audio_samples, kazoo::Encoder< Token_t >::encodeAvailableSymbols(), encoder_, kazoo::SymbolStream< Token_t >::getNumBytes(), kazoo::AudioChannel::getNumSamples(), kazoo::TranslationLayer::Stats::num_bytes, kazoo::TranslationLayer::Stats::num_bytes_encoded, stats_, kazoo::TranslationLayer::Stats::symbols_last_encoded, tx_audio_channel_, and tx_symbol_stream_.
Referenced by sendFrame(), and TEST().
saveWav()
void kazoo::TranslationLayer::saveWav (const std::string & filename)
References kazoo::WavFile::loadFromAudioChannel(), tx_audio_channel_, and kazoo::WavFile::write().
Referenced by TEST().
playAudioBlocking()
void kazoo::TranslationLayer::playAudioBlocking (bool clear_audio_channel = true)
References kazoo::AudioChannel::clear(), kazoo::PulseAudio::Player::play(), and tx_audio_channel_.
Referenced by sendFrame().
loadAndDecodeWav()
void kazoo::TranslationLayer::loadAndDecodeWav (const std::string & filename, std::vector< uint8_t > & data)
References kazoo::ISymbolModel::decodeAudioToSymbols(), kazoo::TranslationLayer::Stats::decoded_was_byte_aligned, kazoo::BinaryStream::getBytes(), kazoo::BinaryStream::getNumBytes(), kazoo::SymbolStream< Token_t >::getNumBytes(), getStaticSymbolModel(), kazoo::BinaryStream::isByteAligned(), KTL_ASSERT, model_type_, kazoo::BinaryStream::pad(), kazoo::WavFile::populateAudioChannel(), kazoo::SymbolStream< Token_t >::populateBinaryStream(), kazoo::WavFile::read(), stats_, tx_audio_channel_, tx_binary_stream_, and tx_symbol_stream_.
startListening()
void kazoo::TranslationLayer::startListening () inline
Starts listening for audio input on the default audio device.
References is_listening_, KTL_ASSERT, listening_thread_, and listeningThreadFunc().
Referenced by main(), and TEST().
stopListening()
void kazoo::TranslationLayer::stopListening () inline
References is_listening_, KTL_ASSERT, and listening_thread_.
Referenced by ~TranslationLayer(), getUserInput(), main(), and TEST().
getReceivedFrame()
std::optional< KtlFrame > kazoo::TranslationLayer::getReceivedFrame () inline
References received_frames_, and received_frames_mutex_.
Referenced by main(), and TEST().
setContinuousMode()
void kazoo::TranslationLayer::setContinuousMode (bool continuous_mode) inline
References is_continuous_mode_.
listeningThreadFunc()
void kazoo::TranslationLayer::listeningThreadFunc () inline private
Todo:
not thread safe
Todo:
References kazoo::AudioChannel::addSamples(), kazoo::AudioChannel::clear(), kazoo::ISymbolModel::decodeAudioToSymbols(), kazoo::BinaryStream::getNumBytes(), kazoo::ISymbolStream::getNumBytes(), kazoo::AudioChannel::getNumSamples(), getStaticSymbolModel(), is_continuous_mode_, is_listening_, kazoo::TranslationLayer::Stats::is_quiet, kazoo::BinaryStream::isByteAligned(), K1_MODEL, K2_PEAK_MODEL, MIN_VOLUME_THRESHOLD, model_ref_, model_type_, kazoo::TranslationLayer::Stats::num_bytes_received, kazoo::TranslationLayer::Stats::num_frames_received, kazoo::BinaryStream::pad(), kazoo::ISymbolStream::populateBinaryStream(), kazoo::TranslationLayer::Stats::pulse_audio_latency_ms, kazoo::TranslationLayer::Stats::pulse_audio_rms, kazoo::TranslationLayer::Stats::pulse_audio_volume, received_frames_, received_frames_mutex_, kazoo::TranslationLayer::Stats::rx_audio_samples, stats_, and stats_mutex_.
Referenced by startListening().
getStaticSymbolModel()
const ISymbolModel & kazoo::TranslationLayer::getStaticSymbolModel (ModelType model_type) static private
References kazoo::BIN_MODEL, BINARY, kazoo::K1_MODEL, K1_MODEL, kazoo::K2_PEAK_MODEL, K2_PEAK_MODEL, kazoo::K3_MODEL, K3_REASONABLE_MODEL, KTL_ASSERT, kazoo::TEST_MODEL, and TESTING.
Referenced by listeningThreadFunc(), and loadAndDecodeWav().
Member Data Documentation
FRAME_PREAMBLE_SIZE
constexpr size_t kazoo::TranslationLayer::FRAME_PREAMBLE_SIZE = 2 static constexpr private
Referenced by sendFrame().
FRAME_POSTAMBLE_SIZE
constexpr size_t kazoo::TranslationLayer::FRAME_POSTAMBLE_SIZE = 2 static constexpr private
Referenced by sendFrame().
MIN_VOLUME_THRESHOLD
constexpr double kazoo::TranslationLayer::MIN_VOLUME_THRESHOLD = 0.01 static constexpr private
The volume threshold below which pulse audio is considered quiet/not receiving audio.
Referenced by listeningThreadFunc().
model_type_
const ModelType kazoo::TranslationLayer::model_type_ private
Referenced by listeningThreadFunc(), and loadAndDecodeWav().
model_ref_
std::reference_wrapper<const ISymbolModel> kazoo::TranslationLayer::model_ref_ private
Initial value:
{
      getStaticSymbolModel(model_type_)}
Referenced by listeningThreadFunc().
tx_symbol_stream_
model::K3ReasonableModel::K3Stream kazoo::TranslationLayer::tx_symbol_stream_ {model_ref_} private
Todo:
This is preventing runtime model selection from working. I'm not going to get to automatic link establishment, so it doesn't matter all that much.
Referenced by addData(), encode(), and loadAndDecodeWav().
encoder_
model::K3ReasonableModel::K3Transcoder kazoo::TranslationLayer::encoder_ {model_ref_} private
Referenced by encode().
tx_binary_stream_
BinaryStream kazoo::TranslationLayer::tx_binary_stream_ private
Referenced by addData(), and loadAndDecodeWav().
tx_audio_channel_
AudioChannel kazoo::TranslationLayer::tx_audio_channel_ private
Referenced by encode(), loadAndDecodeWav(), playAudioBlocking(), saveWav(), and sendFrame().
is_listening_
std::atomic<bool> kazoo::TranslationLayer::is_listening_ {false} private
Referenced by ~TranslationLayer(), listeningThreadFunc(), startListening(), and stopListening().
listening_thread_
std::thread kazoo::TranslationLayer::listening_thread_ {} private
Referenced by startListening(), and stopListening().
is_continuous_mode_
std::atomic<bool> kazoo::TranslationLayer::is_continuous_mode_ {false} private
If false then use the deframer, if true just output the bytes as ASCII as they come in.
Referenced by listeningThreadFunc(), and setContinuousMode().
received_frames_mutex_
std::mutex kazoo::TranslationLayer::received_frames_mutex_ private
Referenced by getReceivedFrame(), and listeningThreadFunc().
received_frames_
std::queue<KtlFrame> kazoo::TranslationLayer::received_frames_ private
Referenced by getReceivedFrame(), and listeningThreadFunc().
stats_mutex_
std::mutex kazoo::TranslationLayer::stats_mutex_ private
Referenced by getStats(), and listeningThreadFunc().
stats_
Stats kazoo::TranslationLayer::stats_ private
Referenced by addData(), encode(), getStats(), listeningThreadFunc(), and loadAndDecodeWav().
The documentation for this class was generated from the following files:
translation_layer.hpp
translation_layer.cpp