Kazooformation: kazoo::Logger Class Reference
kazoo::Logger Class Reference
#include <logger.hpp>
Public Member Functions
Logger (const std::string &logger_name)
Protected Member Functions
void logDebug (const std::string &message)
void logError (const std::string &message)
void logInfo (const std::string &message)
void logWarning (const std::string &message)
Private Member Functions
void log (const std::string &level, const std::string &message)
Private Attributes
std::string logger_name_
Constructor & Destructor Documentation
Logger()
kazoo::Logger::Logger (const std::string & logger_name) inline
Member Function Documentation
logWarning()
void kazoo::Logger::logWarning (const std::string & message) inline protected
References log().
logError()
void kazoo::Logger::logError (const std::string & message) inline protected
References log().
Referenced by kazoo::ModelTester::expectTrue().
logInfo()
void kazoo::Logger::logInfo (const std::string & message) inline protected
References log().
logDebug()
void kazoo::Logger::logDebug (const std::string & message) inline protected
References log().
Referenced by kazoo::ModelTester::runAllTests(), kazoo::ModelTester::test_basicEncodeDecode(), and kazoo::ModelTester::test_gaussianNoiseTolerance().
log()
void kazoo::Logger::log (const std::string & level, const std::string & message) inline private
References logger_name_.
Referenced by logDebug(), logError(), logInfo(), and logWarning().
Member Data Documentation
logger_name_
std::string kazoo::Logger::logger_name_ private
Referenced by log().
The documentation for this class was generated from the following file:
logger.hpp