Kazooformation: kazoo::ISymbolStream Class Reference
kazoo::ISymbolStream Class Reference abstract
An interface for a symbol stream.
#include <i_symbol_stream.hpp>
Public Member Functions
virtual ~ISymbolStream ()=default
virtual void addSymbolId (uint32_t symbol_id)=0
virtual void clear ()=0
Clear/Reset the symbol stream.
virtual size_t getNumBytes () const =0
virtual bool popSymbolTokenId (uint32_t &token_id)=0
virtual bool populateBinaryStream (BinaryStream &binary_stream, size_t num_bytes, bool pop_symbols=true)=0
virtual std::pair< size_t, size_t > processBinaryStream (BinaryStream &binary_stream)=0
Detailed Description
An interface for a symbol stream.
Constructor & Destructor Documentation
~ISymbolStream()
virtual kazoo::ISymbolStream::~ISymbolStream () virtual default
Member Function Documentation
clear()
virtual void kazoo::ISymbolStream::clear () pure virtual
Clear/Reset the symbol stream.
Implemented in kazoo::SymbolStream< Token_t >, and kazoo::SymbolStream< Token >.
Referenced by kazoo::ModelTester::helper_decodeAudioChannelToString(), kazoo::ModelTester::resetState(), and kazoo::ModelTester::test_basicEncodeDecode().
addSymbolId()
virtual void kazoo::ISymbolStream::addSymbolId (uint32_t symbol_id) pure virtual
Implemented in kazoo::SymbolStream< Token_t >, and kazoo::SymbolStream< Token >.
Referenced by kazoo::model::K1Model::Model::decodeAudioToSymbols(), kazoo::model::K2PeakModel::Model::decodeAudioToSymbols(), kazoo::model::K3ReasonableModel::K3Model::decodeAudioToSymbols(), and kazoo::model::Testing::Model::decodeAudioToSymbols().
getNumBytes()
virtual size_t kazoo::ISymbolStream::getNumBytes () const pure virtual
Implemented in kazoo::SymbolStream< Token_t >, and kazoo::SymbolStream< Token >.
Referenced by kazoo::ModelTester::helper_encodeStringToAudioChannel(), kazoo::TranslationLayer::listeningThreadFunc(), and kazoo::ModelTester::test_basicEncodeDecode().
populateBinaryStream()
virtual bool kazoo::ISymbolStream::populateBinaryStream (BinaryStream & binary_stream, size_t num_bytes, bool pop_symbols = true) pure virtual
Implemented in kazoo::SymbolStream< Token_t >, and kazoo::SymbolStream< Token >.
Referenced by kazoo::ModelTester::helper_decodeAudioChannelToString(), kazoo::TranslationLayer::listeningThreadFunc(), and kazoo::ModelTester::test_basicEncodeDecode().
processBinaryStream()
virtual std::pair< size_t, size_t > kazoo::ISymbolStream::processBinaryStream (BinaryStream & binary_stream) pure virtual
Implemented in kazoo::SymbolStream< Token_t >, and kazoo::SymbolStream< Token >.
Referenced by kazoo::ModelTester::helper_encodeStringToAudioChannel(), and kazoo::ModelTester::test_basicEncodeDecode().
popSymbolTokenId()
virtual bool kazoo::ISymbolStream::popSymbolTokenId (uint32_t & token_id) pure virtual
Implemented in kazoo::SymbolStream< Token_t >, and kazoo::SymbolStream< Token >.
Referenced by kazoo::Encoder< Token_t >::encodeAvailableSymbols().
The documentation for this class was generated from the following file:
i_symbol_stream.hpp