Kazooformation: k1_model.test.cpp File Reference
k1_model.test.cpp File Reference
#include <filesystem>
#include <testing.hpp>
#include <ktl/audio/audio_channel.hpp>
#include <ktl/audio/wav_file.hpp>
#include <ktl/audio/wave_tools.hpp>
#include <ktl/encoder.hpp>
#include <ktl/models/k1_model.hpp>
Classes
class K1Model_test
Functions
TEST_F (K1Model_test, decode_misaligned)
TEST_F (K1Model_test, encode_and_decode)
Detailed Description
Author
Joshua Jerred
Copyright
Copyright (c) 2025
Date
2025-02-02
Function Documentation
TEST_F() [1/2]
TEST_F (K1Model_test , encode_and_decode)
References kazoo::SymbolStream< Token_t >::addSymbol(), kazoo::model::K1Model::Model::decodeAudioToSymbols(), kazoo::AudioChannel::getNumSamples(), kazoo::WavFile::getNumSamples(), kazoo::WavFile::loadFromAudioChannel(), kazoo::WavFile::read(), kazoo::model::K1Model::SAMPLES_PER_SYMBOL, and kazoo::WavFile::write().
TEST_F() [2/2]
TEST_F (K1Model_test , decode_misaligned)
References kazoo::WaveTools::addGaussianNoise(), kazoo::SymbolStream< Token_t >::addSymbol(), kazoo::model::K1Model::Model::decodeAudioToSymbols(), kazoo::AudioChannel::getNumSamples(), kazoo::WavFile::getNumSamples(), kazoo::WavFile::loadFromAudioChannel(), kazoo::WavFile::read(), kazoo::model::K1Model::SAMPLES_PER_SYMBOL, and kazoo::WavFile::write().