Kazooformation: k2_peak_model.test.cpp File Reference
k2_peak_model.test.cpp File Reference
#include <filesystem>
#include <testing.hpp>
#include <ktl/audio/audio_channel.hpp>
#include <ktl/audio/wav_file.hpp>
#include <ktl/audio/wave_tools.hpp>
#include <ktl/encoder.hpp>
#include <ktl/models/k2/k2_model.hpp>
Classes
class K2PeakModel_test
Functions
TEST_F (K2PeakModel_test, decode_misaligned)
TEST_F (K2PeakModel_test, encode_and_decode)
Function Documentation
TEST_F() [1/2]
TEST_F (K2PeakModel_test , encode_and_decode)
References kazoo::SymbolStream< Token_t >::addSymbol(), kazoo::model::K2PeakModel::Model::decodeAudioToSymbols(), kazoo::AudioChannel::getNumSamples(), kazoo::WavFile::getNumSamples(), kazoo::WavFile::loadFromAudioChannel(), kazoo::WavFile::read(), kazoo::model::K2PeakModel::SAMPLES_PER_SYMBOL, and kazoo::WavFile::write().
TEST_F() [2/2]
TEST_F (K2PeakModel_test , decode_misaligned)
References kazoo::WaveTools::addGaussianNoise(), kazoo::SymbolStream< Token_t >::addSymbol(), kazoo::model::K2PeakModel::Model::decodeAudioToSymbols(), kazoo::AudioChannel::getNumSamples(), kazoo::WavFile::getNumSamples(), kazoo::WavFile::loadFromAudioChannel(), kazoo::WavFile::read(), kazoo::model::K2PeakModel::SAMPLES_PER_SYMBOL, and kazoo::WavFile::write().