Kazooformation: main.cpp File Reference
src/main.cpp File Reference
#include <atomic>
#include <chrono>
#include <iostream>
#include <string>
#include <thread>
#include <ktl/translation_layer.hpp>
Functions
void getUserInput ()
int main ()
Variables
constexpr bool CHAT_MODE = true
constexpr bool PRE_POST_PADDING = true
std::atomic< bool > s_have_user_input {false}
std::atomic< bool > s_run_flag {true}
static std::atomic< bool > s_rx_during_tx_mode = true
when true we keep rxing when txing, nice for testing as you only need one client on the loopback. Toggle with "rx" command
static std::string s_user_input = ""
kazoo::TranslationLayer tl {kazoo::TranslationLayer::ModelType::K3_REASONABLE_MODEL}
Detailed Description
Author
Joshua Jerred
Copyright
Copyright (c) 2025
Date
2025-03-13
Function Documentation
getUserInput()
void getUserInput ()
Todo:
There may no longer be a need for this.
References s_have_user_input, s_run_flag, s_rx_during_tx_mode, s_user_input, kazoo::TranslationLayer::stopListening(), and tl.
Referenced by main().
main()
int main ()
References CHAT_MODE, kazoo::TranslationLayer::getReceivedFrame(), kazoo::TranslationLayer::getStats(), getUserInput(), s_have_user_input, s_run_flag, s_rx_during_tx_mode, s_user_input, kazoo::TranslationLayer::sendFrame(), kazoo::TranslationLayer::startListening(), kazoo::TranslationLayer::stopListening(), and tl.
Variable Documentation
CHAT_MODE
constexpr bool CHAT_MODE = true constexpr
Referenced by main().
PRE_POST_PADDING
constexpr bool PRE_POST_PADDING = true constexpr
s_run_flag
std::atomic<bool> s_run_flag {true}
Referenced by getUserInput(), and main().
s_have_user_input
std::atomic<bool> s_have_user_input {false}
Referenced by getUserInput(), and main().
s_user_input
std::string s_user_input = "" static
Referenced by getUserInput(), and main().
s_rx_during_tx_mode
std::atomic<bool> s_rx_during_tx_mode = true static
when true we keep rxing when txing, nice for testing as you only need one client on the loopback. Toggle with "rx" command
Referenced by getUserInput(), and main().
tl
kazoo::TranslationLayer tl {kazoo::TranslationLayer::ModelType::K3_REASONABLE_MODEL}
Referenced by getUserInput(), main(), and TEST().