Kazooformation: main.cpp File Reference
src/kazoo_connect_server/main.cpp File Reference
#include <chrono>
#include <iostream>
#include <string>
#include <thread>
#include <vector>
#include "tcp_socket.hpp"
#include <ktl/translation_layer.hpp>
Classes
struct HttpResponse
Functions
static void debug (const std::string &message)
void httpServerThread ()
One of the HTTP servers of all time.
int main ()
Variables
kazoo::TranslationLayer s_kazooformation
static std::mutex s_messages_mutex
static std::vector< std::string > s_messages_received = {}
static std::vector< std::string > s_messages_to_send = {}
static std::atomic< bool > s_sending_audio {false}
constexpr int SERVER_PORT = 8082
Detailed Description
Author
Joshua Jerred
Copyright
Copyright (c) 2025
Date
2025-04-11
Function Documentation
debug()
static void debug (const std::string & message) static
Referenced by httpServerThread().
httpServerThread()
void httpServerThread ()
One of the HTTP servers of all time.
Todo:
confirm this behavior with spec
References sock::TcpSocketServer::accept(), HttpResponse::body, debug(), HttpResponse::getResponse(), sock::TcpSocketServer::init(), sock::TcpSocketServer::receive(), s_messages_mutex, s_messages_received, s_messages_to_send, s_sending_audio, sock::TcpSocketServer::send(), and SERVER_PORT.
Referenced by main().
main()
int main ()
Todo:
catch the ctrl+c signal and exit gracefully
References kazoo::TranslationLayer::getReceivedFrame(), httpServerThread(), s_kazooformation, s_messages_mutex, s_messages_received, s_messages_to_send, s_sending_audio, kazoo::TranslationLayer::sendFrame(), SERVER_PORT, and kazoo::TranslationLayer::startListening().
Variable Documentation
SERVER_PORT
constexpr int SERVER_PORT = 8082 inline constexpr
Referenced by httpServerThread(), and main().
s_messages_mutex
std::mutex s_messages_mutex static
Referenced by httpServerThread(), and main().
s_messages_to_send
std::vector<std::string> s_messages_to_send = {} static
Referenced by httpServerThread(), and main().
s_messages_received
std::vector<std::string> s_messages_received = {} static
Referenced by httpServerThread(), and main().
s_sending_audio
std::atomic<bool> s_sending_audio {false} static
Referenced by httpServerThread(), and main().
s_kazooformation
kazoo::TranslationLayer s_kazooformation
Initial value:
{
    kazoo::TranslationLayer::ModelType::K3_REASONABLE_MODEL}
Referenced by main().