Kazooformation: symbol_stream.test.cpp File Reference
symbol_stream.test.cpp File Reference
#include <testing.hpp>
#include <ktl/binary_stream.hpp>
#include <ktl/models/symbol_model.hpp>
#include <ktl/symbol_stream.hpp>
Enumerations
enum class TestToken : uint32_t {
UNKNOWN = 0 , SYMBOL_00 , SYMBOL_01 , SYMBOL_10 ,
SYMBOL_11 , _SYMBOL_COUNT
}
Functions
TEST (SymbolStream_test, addSymbols)
TEST (SymbolStream_test, arrayValidation)
TEST (SymbolStream_test, populateBinaryStream)
TEST (SymbolStream_test, processBinaryStream)
Variables
static const kazoo::SymbolModel< TestToken > TEST_SYMBOL_MODEL
Enumeration Type Documentation
TestToken
enum class TestToken : uint32_t strong
Enumerator
UNKNOWN
SYMBOL_00
SYMBOL_01
SYMBOL_10
SYMBOL_11
_SYMBOL_COUNT
Function Documentation
TEST() [1/4]
TEST (SymbolStream_test , addSymbols)
References kazoo::SymbolStream< Token_t >::addSymbol(), kazoo::SymbolStream< Token_t >::getNumBits(), kazoo::SymbolStream< Token_t >::getNumBytes(), kazoo::SymbolStream< Token_t >::getNumSymbols(), SYMBOL_00, SYMBOL_10, SYMBOL_11, and TEST_SYMBOL_MODEL.
TEST() [2/4]
TEST (SymbolStream_test , populateBinaryStream)
References kazoo::SymbolStream< Token_t >::addSymbol(), kazoo::BinaryStream::getNumBits(), kazoo::BinaryStream::getStreamDataConst(), kazoo::SymbolStream< Token_t >::populateBinaryStream(), SYMBOL_01, SYMBOL_10, SYMBOL_11, and TEST_SYMBOL_MODEL.
TEST() [3/4]
TEST (SymbolStream_test , processBinaryStream)
References kazoo::BinaryStream::addBits(), kazoo::BinaryStream::getNumBytes(), kazoo::SymbolStream< Token_t >::popSymbol(), kazoo::SymbolStream< Token_t >::processBinaryStream(), SYMBOL_00, SYMBOL_01, SYMBOL_10, SYMBOL_11, and TEST_SYMBOL_MODEL.
TEST() [4/4]
TEST (SymbolStream_test , arrayValidation)
Test:
Validate that an array can be converted to and from symbols.
References kazoo::BinaryStream::addBytes(), kazoo::SymbolStream< Token_t >::addSymbol(), kazoo::SymbolStream< Token_t >::getNumBits(), kazoo::BinaryStream::getNumBytes(), kazoo::SymbolStream< Token_t >::getNumBytes(), kazoo::SymbolStream< Token_t >::getNumSymbols(), kazoo::BinaryStream::getStreamDataConst(), kazoo::SymbolStream< Token_t >::popSymbol(), kazoo::SymbolStream< Token_t >::populateBinaryStream(), kazoo::SymbolStream< Token_t >::processBinaryStream(), and TEST_SYMBOL_MODEL.
Variable Documentation
TEST_SYMBOL_MODEL
const kazoo::SymbolModel<TestToken> TEST_SYMBOL_MODEL static
Initial value:
{
    {{TestToken::SYMBOL_00, 0},
     {TestToken::SYMBOL_01, 1},
     {TestToken::SYMBOL_10, 2},
     {TestToken::SYMBOL_11, 3}},
    2}
Referenced by TEST().