Kazooformation: main.cpp File Reference
tests/ktl_model_scoring/main.cpp File Reference
#include <array>
#include <iostream>
#include <random>
#include <vector>
#include "model_tester.hpp"
#include <ktl/models/k1_model.hpp>
#include <ktl/models/k2/k2_model.hpp>
Functions
double k1Test ()
double k2Test ()
int main ()
Detailed Description
Author
Joshua Jerred
Copyright
Copyright (c) 2025
Date
2025-03-14
Function Documentation
k1Test()
double k1Test ()
Referenced by main().
k2Test()
double k2Test ()
Referenced by main().
main()
int main ()
References k1Test(), and k2Test().