Kazooformation: translation_layer.test.cpp File Reference
translation_layer.test.cpp File Reference
#include <array>
#include <testing.hpp>
#include <ktl/translation_layer.hpp>
Functions
TEST (TranslationLayer_test, encode_and_decode_wav)
TEST (TranslationLayer_test, encode_to_wav)
TEST (TranslationLayer_test, kazoo_hello_world_pulse)
TEST (TranslationLayer_test, kazoo_hello_world_wav)
Detailed Description
Author
Joshua Jerred
Copyright
Copyright (c) 2025
Date
2025-01-25
Function Documentation
TEST() [1/4]
TEST (TranslationLayer_test , encode_to_wav)
References kazoo::TranslationLayer::addData(), kazoo::TranslationLayer::encode(), kazoo::TranslationLayer::getStats(), kazoo::TranslationLayer::Stats::num_bytes, kazoo::TranslationLayer::saveWav(), kazoo::TranslationLayer::Stats::symbols_last_encoded, kazoo::TranslationLayer::TESTING, and tl.
TEST() [2/4]
TEST (TranslationLayer_test , encode_and_decode_wav)
References kazoo::TranslationLayer::addData(), kazoo::TranslationLayer::encode(), kazoo::TranslationLayer::getStats(), kazoo::TranslationLayer::K1_MODEL, kazoo::TranslationLayer::Stats::num_bytes, kazoo::TranslationLayer::saveWav(), kazoo::TranslationLayer::Stats::symbols_last_encoded, and tl.
TEST() [3/4]
TEST (TranslationLayer_test , kazoo_hello_world_wav)
Test:
The very first test with actual kazoo symbols
References kazoo::TranslationLayer::addData(), kazoo::TranslationLayer::encode(), kazoo::TranslationLayer::K1_MODEL, kazoo::TranslationLayer::saveWav(), and tl.
TEST() [4/4]
TEST (TranslationLayer_test , kazoo_hello_world_pulse)
Test:
The very first test with actual kazoo symbols
References kazoo::TranslationLayer::getReceivedFrame(), kazoo::TranslationLayer::getStats(), kazoo::TranslationLayer::K1_MODEL, kazoo::TranslationLayer::sendFrame(), kazoo::TranslationLayer::startListening(), kazoo::TranslationLayer::stopListening(), and tl.