@startuml "KTL Flow Diagram"
left to right direction

component "Any Serialized\nByte Data\nor KtlFrame" as SerializedData
component BinaryStream
package SymbolModel {
  component SymbolStream

  component SymbolTable
  component "Encoder/Decoder" as EncoderDecoder
  SymbolStream .left. EncoderDecoder
  SymbolStream .right. SymbolTable
}
component AudioChannel

SerializedData <--> BinaryStream
BinaryStream <--> SymbolStream
SymbolStream <--> AudioChannel

@enduml